/*
 * Omega.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * OmegaAPIAreasPublicModelsReponsesDefaultResponseOmegaAPIAreasPublicModelsPublicSearchResultOmegaAPIAreasEnterpriseOmegaModelsDocumentsExpenseExpenseOmegaAPIAreasPublicModelsPublicExpenseModel
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-12-27T17:23:48.058+02:00")
public class OmegaAPIAreasPublicModelsReponsesDefaultResponseOExpenseModel {
  @SerializedName("Data")
  private OmegaAPIAreasPublicModelsPublicSearchResultOmegaAPIAreasEnterpriseOmegaModelsDocumentsExpenseExpenseOmegaAPIAreasPublicModelsPublicExpenseModel data = null;

  @SerializedName("Success")
  private Boolean success = null;

  @SerializedName("Errors")
  private List<OmegaCommonModelsResponsesError> errors = null;

  public OmegaAPIAreasPublicModelsReponsesDefaultResponseOExpenseModel data(OmegaAPIAreasPublicModelsPublicSearchResultOmegaAPIAreasEnterpriseOmegaModelsDocumentsExpenseExpenseOmegaAPIAreasPublicModelsPublicExpenseModel data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @ApiModelProperty(value = "")
  public OmegaAPIAreasPublicModelsPublicSearchResultOmegaAPIAreasEnterpriseOmegaModelsDocumentsExpenseExpenseOmegaAPIAreasPublicModelsPublicExpenseModel getData() {
    return data;
  }

  public void setData(OmegaAPIAreasPublicModelsPublicSearchResultOmegaAPIAreasEnterpriseOmegaModelsDocumentsExpenseExpenseOmegaAPIAreasPublicModelsPublicExpenseModel data) {
    this.data = data;
  }

  public OmegaAPIAreasPublicModelsReponsesDefaultResponseOExpenseModel success(Boolean success) {
    this.success = success;
    return this;
  }

   /**
   * Get success
   * @return success
  **/
  @ApiModelProperty(value = "")
  public Boolean getSuccess() {
    return success;
  }

  public void setSuccess(Boolean success) {
    this.success = success;
  }

  public OmegaAPIAreasPublicModelsReponsesDefaultResponseOExpenseModel errors(List<OmegaCommonModelsResponsesError> errors) {
    this.errors = errors;
    return this;
  }

  public OmegaAPIAreasPublicModelsReponsesDefaultResponseOExpenseModel addErrorsItem(OmegaCommonModelsResponsesError errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<OmegaCommonModelsResponsesError>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * Get errors
   * @return errors
  **/
  @ApiModelProperty(value = "")
  public List<OmegaCommonModelsResponsesError> getErrors() {
    return errors;
  }

  public void setErrors(List<OmegaCommonModelsResponsesError> errors) {
    this.errors = errors;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OmegaAPIAreasPublicModelsReponsesDefaultResponseOExpenseModel omegaAPIAreasPublicModelsReponsesDefaultResponseOExpenseModel = (OmegaAPIAreasPublicModelsReponsesDefaultResponseOExpenseModel) o;
    return Objects.equals(this.data, omegaAPIAreasPublicModelsReponsesDefaultResponseOExpenseModel.data) &&
        Objects.equals(this.success, omegaAPIAreasPublicModelsReponsesDefaultResponseOExpenseModel.success) &&
        Objects.equals(this.errors, omegaAPIAreasPublicModelsReponsesDefaultResponseOExpenseModel.errors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, success, errors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OmegaAPIAreasPublicModelsReponsesDefaultResponseOmegaAPIAreasPublicModelsPublicSearchResultOmegaAPIAreasEnterpriseOmegaModelsDocumentsExpenseExpenseOmegaAPIAreasPublicModelsPublicExpenseModel {\n");
    
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

