/*
 * Omega.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * OmegaAPIAreasPublicModelsClaimPublicClaimPhoto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-12-27T17:23:48.058+02:00")
public class OmegaAPIAreasPublicModelsClaimPublicClaimPhoto {
  @SerializedName("Ref_Key")
  private String refKey = null;

  @SerializedName("Owner_Key")
  private String ownerKey = null;

  @SerializedName("FileName")
  private String fileName = null;

  @SerializedName("Code")
  private String code = null;

  @SerializedName("LineNum")
  private String lineNum = null;

  @SerializedName("DocReasonId")
  private String docReasonId = null;

  @SerializedName("FileNameOriginal")
  private String fileNameOriginal = null;

  public OmegaAPIAreasPublicModelsClaimPublicClaimPhoto refKey(String refKey) {
    this.refKey = refKey;
    return this;
  }

   /**
   * Get refKey
   * @return refKey
  **/
  @ApiModelProperty(value = "")
  public String getRefKey() {
    return refKey;
  }

  public void setRefKey(String refKey) {
    this.refKey = refKey;
  }

  public OmegaAPIAreasPublicModelsClaimPublicClaimPhoto ownerKey(String ownerKey) {
    this.ownerKey = ownerKey;
    return this;
  }

   /**
   * Get ownerKey
   * @return ownerKey
  **/
  @ApiModelProperty(value = "")
  public String getOwnerKey() {
    return ownerKey;
  }

  public void setOwnerKey(String ownerKey) {
    this.ownerKey = ownerKey;
  }

  public OmegaAPIAreasPublicModelsClaimPublicClaimPhoto fileName(String fileName) {
    this.fileName = fileName;
    return this;
  }

   /**
   * Get fileName
   * @return fileName
  **/
  @ApiModelProperty(value = "")
  public String getFileName() {
    return fileName;
  }

  public void setFileName(String fileName) {
    this.fileName = fileName;
  }

  public OmegaAPIAreasPublicModelsClaimPublicClaimPhoto code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @ApiModelProperty(value = "")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public OmegaAPIAreasPublicModelsClaimPublicClaimPhoto lineNum(String lineNum) {
    this.lineNum = lineNum;
    return this;
  }

   /**
   * Get lineNum
   * @return lineNum
  **/
  @ApiModelProperty(value = "")
  public String getLineNum() {
    return lineNum;
  }

  public void setLineNum(String lineNum) {
    this.lineNum = lineNum;
  }

  public OmegaAPIAreasPublicModelsClaimPublicClaimPhoto docReasonId(String docReasonId) {
    this.docReasonId = docReasonId;
    return this;
  }

   /**
   * Get docReasonId
   * @return docReasonId
  **/
  @ApiModelProperty(value = "")
  public String getDocReasonId() {
    return docReasonId;
  }

  public void setDocReasonId(String docReasonId) {
    this.docReasonId = docReasonId;
  }

  public OmegaAPIAreasPublicModelsClaimPublicClaimPhoto fileNameOriginal(String fileNameOriginal) {
    this.fileNameOriginal = fileNameOriginal;
    return this;
  }

   /**
   * Get fileNameOriginal
   * @return fileNameOriginal
  **/
  @ApiModelProperty(value = "")
  public String getFileNameOriginal() {
    return fileNameOriginal;
  }

  public void setFileNameOriginal(String fileNameOriginal) {
    this.fileNameOriginal = fileNameOriginal;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OmegaAPIAreasPublicModelsClaimPublicClaimPhoto omegaAPIAreasPublicModelsClaimPublicClaimPhoto = (OmegaAPIAreasPublicModelsClaimPublicClaimPhoto) o;
    return Objects.equals(this.refKey, omegaAPIAreasPublicModelsClaimPublicClaimPhoto.refKey) &&
        Objects.equals(this.ownerKey, omegaAPIAreasPublicModelsClaimPublicClaimPhoto.ownerKey) &&
        Objects.equals(this.fileName, omegaAPIAreasPublicModelsClaimPublicClaimPhoto.fileName) &&
        Objects.equals(this.code, omegaAPIAreasPublicModelsClaimPublicClaimPhoto.code) &&
        Objects.equals(this.lineNum, omegaAPIAreasPublicModelsClaimPublicClaimPhoto.lineNum) &&
        Objects.equals(this.docReasonId, omegaAPIAreasPublicModelsClaimPublicClaimPhoto.docReasonId) &&
        Objects.equals(this.fileNameOriginal, omegaAPIAreasPublicModelsClaimPublicClaimPhoto.fileNameOriginal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(refKey, ownerKey, fileName, code, lineNum, docReasonId, fileNameOriginal);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OmegaAPIAreasPublicModelsClaimPublicClaimPhoto {\n");
    
    sb.append("    refKey: ").append(toIndentedString(refKey)).append("\n");
    sb.append("    ownerKey: ").append(toIndentedString(ownerKey)).append("\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    lineNum: ").append(toIndentedString(lineNum)).append("\n");
    sb.append("    docReasonId: ").append(toIndentedString(docReasonId)).append("\n");
    sb.append("    fileNameOriginal: ").append(toIndentedString(fileNameOriginal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

