/*
 * Omega.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.OmegaAPIAreasEnterpriseOmegaModelsCatalogsProductDirection;
import io.swagger.client.model.OmegaAPIAreasEnterpriseOmegaModelsCatalogsProductLine;
import io.swagger.client.model.OmegaAPIAreasEnterpriseOmegaModelsCatalogsSegment;
import java.io.IOException;

/**
 * OmegaAPIAreasEnterpriseOmegaModelsCatalogsProduct
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-12-27T17:23:48.058+02:00")
public class OmegaAPIAreasEnterpriseOmegaModelsCatalogsProduct {
  @SerializedName("Ref_Key")
  private String refKey = null;

  @SerializedName("Карточка")
  private String Kartochka = null;

  @SerializedName("Code")
  private String code = null;

  @SerializedName("КодПоКаталогу")
  private String codPoCatalogu = null;

  @SerializedName("Description")
  private String description = null;


  @SerializedName("Ид77")
  private String ID_77 = null;

  @SerializedName("ART_ID")
  private String ART_ID = null;

  @SerializedName("ArtIdCalc")
  private String artIdCalc = null;

  @SerializedName("Сегмент_Key")
  private String key = null;

  @SerializedName("КоличествоМинимальногоРозничногоЗапаса")
  private Double kolMinRoznZakaza = null;

  @SerializedName("МассаДетали")
  private Double massDetail = null;

  @SerializedName("Segment")
  private OmegaAPIAreasEnterpriseOmegaModelsCatalogsSegment segment = null;

  @SerializedName("ProductLine")
  private OmegaAPIAreasEnterpriseOmegaModelsCatalogsProductLine productLine = null;

  @SerializedName("ProductDirection")
  private OmegaAPIAreasEnterpriseOmegaModelsCatalogsProductDirection productDirection = null;

  public OmegaAPIAreasEnterpriseOmegaModelsCatalogsProduct refKey(String refKey) {
    this.refKey = refKey;
    return this;
  }

   /**
   * Get refKey
   * @return refKey
  **/
  @ApiModelProperty(value = "")
  public String getRefKey() {
    return refKey;
  }

  public void setRefKey(String refKey) {
    this.refKey = refKey;
  }



   /**
   * Get 
   * @return 
  **/
  @ApiModelProperty(value = "")
  public OmegaAPIAreasEnterpriseOmegaModelsCatalogsProduct code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @ApiModelProperty(value = "")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }


   /**
   * Get 
   * @return 
  **/


  public OmegaAPIAreasEnterpriseOmegaModelsCatalogsProduct description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }



   /**
   * Get 
   * @return 
  **/
  @ApiModelProperty(value = "")
  public OmegaAPIAreasEnterpriseOmegaModelsCatalogsProduct ID_77(String ID_77) {
    this.ID_77 = ID_77;
    return this;
  }

   /**
   * Get _77
   * @return _77
  **/
  @ApiModelProperty(value = "")
  public String getID_77() {
    return ID_77;
  }

  public void set77(String _77) {
    this.ID_77 = ID_77;
  }

  public OmegaAPIAreasEnterpriseOmegaModelsCatalogsProduct ART_ID(String ART_ID) {
    this.ART_ID = ART_ID;
    return this;
  }

   /**
   * Get ART_ID
   * @return ART_ID
  **/
  @ApiModelProperty(value = "")
  public String getARTID() {
    return ART_ID;
  }

  public void setARTID(String ART_ID) {
    this.ART_ID = ART_ID;
  }

   /**
   * Get artIdCalc
   * @return artIdCalc
  **/
  @ApiModelProperty(value = "")
  public String getArtIdCalc() {
    return artIdCalc;
  }

  public OmegaAPIAreasEnterpriseOmegaModelsCatalogsProduct key(String key) {
    this.key = key;
    return this;
  }

   /**
   * Get key
   * @return key
  **/
  @ApiModelProperty(value = "")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }



   /**
   * Get 
   * @return 
  **/


   /**
   * Get 
   * @return 
  **/
  @ApiModelProperty(value = "")

  public OmegaAPIAreasEnterpriseOmegaModelsCatalogsProduct segment(OmegaAPIAreasEnterpriseOmegaModelsCatalogsSegment segment) {
    this.segment = segment;
    return this;
  }

   /**
   * Get segment
   * @return segment
  **/
  @ApiModelProperty(value = "")
  public OmegaAPIAreasEnterpriseOmegaModelsCatalogsSegment getSegment() {
    return segment;
  }

  public void setSegment(OmegaAPIAreasEnterpriseOmegaModelsCatalogsSegment segment) {
    this.segment = segment;
  }

  public OmegaAPIAreasEnterpriseOmegaModelsCatalogsProduct productLine(OmegaAPIAreasEnterpriseOmegaModelsCatalogsProductLine productLine) {
    this.productLine = productLine;
    return this;
  }

   /**
   * Get productLine
   * @return productLine
  **/
  @ApiModelProperty(value = "")
  public OmegaAPIAreasEnterpriseOmegaModelsCatalogsProductLine getProductLine() {
    return productLine;
  }

  public void setProductLine(OmegaAPIAreasEnterpriseOmegaModelsCatalogsProductLine productLine) {
    this.productLine = productLine;
  }

  public OmegaAPIAreasEnterpriseOmegaModelsCatalogsProduct productDirection(OmegaAPIAreasEnterpriseOmegaModelsCatalogsProductDirection productDirection) {
    this.productDirection = productDirection;
    return this;
  }

   /**
   * Get productDirection
   * @return productDirection
  **/
  @ApiModelProperty(value = "")
  public OmegaAPIAreasEnterpriseOmegaModelsCatalogsProductDirection getProductDirection() {
    return productDirection;
  }

  public void setProductDirection(OmegaAPIAreasEnterpriseOmegaModelsCatalogsProductDirection productDirection) {
    this.productDirection = productDirection;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OmegaAPIAreasEnterpriseOmegaModelsCatalogsProduct omegaAPIAreasEnterpriseOmegaModelsCatalogsProduct = (OmegaAPIAreasEnterpriseOmegaModelsCatalogsProduct) o;
    return Objects.equals(this.refKey, omegaAPIAreasEnterpriseOmegaModelsCatalogsProduct.refKey) &&
        Objects.equals(this.code, omegaAPIAreasEnterpriseOmegaModelsCatalogsProduct.code) &&
        Objects.equals(this.description, omegaAPIAreasEnterpriseOmegaModelsCatalogsProduct.description) &&
        Objects.equals(this.ID_77, omegaAPIAreasEnterpriseOmegaModelsCatalogsProduct.ID_77) &&
        Objects.equals(this.ART_ID, omegaAPIAreasEnterpriseOmegaModelsCatalogsProduct.ART_ID) &&
        Objects.equals(this.artIdCalc, omegaAPIAreasEnterpriseOmegaModelsCatalogsProduct.artIdCalc) &&
        Objects.equals(this.key, omegaAPIAreasEnterpriseOmegaModelsCatalogsProduct.key) &&
        Objects.equals(this.segment, omegaAPIAreasEnterpriseOmegaModelsCatalogsProduct.segment) &&
        Objects.equals(this.productLine, omegaAPIAreasEnterpriseOmegaModelsCatalogsProduct.productLine) &&
        Objects.equals(this.productDirection, omegaAPIAreasEnterpriseOmegaModelsCatalogsProduct.productDirection);
  }

  @Override
  public int hashCode() {
    return Objects.hash(refKey, code, description, ID_77, ART_ID, artIdCalc, key, segment, productLine, productDirection);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OmegaAPIAreasEnterpriseOmegaModelsCatalogsProduct {\n");
    
    sb.append("    refKey: ").append(toIndentedString(refKey)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    _77: ").append(toIndentedString(ID_77)).append("\n");
    sb.append("    ART_ID: ").append(toIndentedString(ART_ID)).append("\n");
    sb.append("    artIdCalc: ").append(toIndentedString(artIdCalc)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    segment: ").append(toIndentedString(segment)).append("\n");
    sb.append("    productLine: ").append(toIndentedString(productLine)).append("\n");
    sb.append("    productDirection: ").append(toIndentedString(productDirection)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

