/*
 * Omega.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * OmegaAPIAreasPublicModelsPublicExpenseCourier
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-12-27T17:23:48.058+02:00")
public class OmegaAPIAreasPublicModelsPublicExpenseCourier {
  @SerializedName("CourierDelivery")
  private String courierDelivery = null;

  @SerializedName("Locality")
  private String locality = null;

  public OmegaAPIAreasPublicModelsPublicExpenseCourier courierDelivery(String courierDelivery) {
    this.courierDelivery = courierDelivery;
    return this;
  }

   /**
   * Вид курьерской доставки
   * @return courierDelivery
  **/
  @ApiModelProperty(value = "Вид курьерской доставки")
  public String getCourierDelivery() {
    return courierDelivery;
  }

  public void setCourierDelivery(String courierDelivery) {
    this.courierDelivery = courierDelivery;
  }

  public OmegaAPIAreasPublicModelsPublicExpenseCourier locality(String locality) {
    this.locality = locality;
    return this;
  }

   /**
   * Адрес
   * @return locality
  **/
  @ApiModelProperty(value = "Адрес")
  public String getLocality() {
    return locality;
  }

  public void setLocality(String locality) {
    this.locality = locality;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OmegaAPIAreasPublicModelsPublicExpenseCourier omegaAPIAreasPublicModelsPublicExpenseCourier = (OmegaAPIAreasPublicModelsPublicExpenseCourier) o;
    return Objects.equals(this.courierDelivery, omegaAPIAreasPublicModelsPublicExpenseCourier.courierDelivery) &&
        Objects.equals(this.locality, omegaAPIAreasPublicModelsPublicExpenseCourier.locality);
  }

  @Override
  public int hashCode() {
    return Objects.hash(courierDelivery, locality);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OmegaAPIAreasPublicModelsPublicExpenseCourier {\n");
    
    sb.append("    courierDelivery: ").append(toIndentedString(courierDelivery)).append("\n");
    sb.append("    locality: ").append(toIndentedString(locality)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

