/*
 * Omega.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.OmegaAPIAreasPublicModelsRequestModelsKeyValuePublic;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * OmegaAPIAreasPublicModelsRequestModelsAddProductListParametersRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-12-27T17:23:48.058+02:00")
public class OmegaAPIAreasPublicModelsRequestModelsAddProductListParametersRequest {
  @SerializedName("ProductList")
  private List<OmegaAPIAreasPublicModelsRequestModelsKeyValuePublic> productList = new ArrayList<OmegaAPIAreasPublicModelsRequestModelsKeyValuePublic>();

  @SerializedName("Key")
  private String key = null;

  public OmegaAPIAreasPublicModelsRequestModelsAddProductListParametersRequest productList(List<OmegaAPIAreasPublicModelsRequestModelsKeyValuePublic> productList) {
    this.productList = productList;
    return this;
  }

  public OmegaAPIAreasPublicModelsRequestModelsAddProductListParametersRequest addProductListItem(OmegaAPIAreasPublicModelsRequestModelsKeyValuePublic productListItem) {
    this.productList.add(productListItem);
    return this;
  }

   /**
   * Список товаров
   * @return productList
  **/
  @ApiModelProperty(required = true, value = "Список товаров")
  public List<OmegaAPIAreasPublicModelsRequestModelsKeyValuePublic> getProductList() {
    return productList;
  }

  public void setProductList(List<OmegaAPIAreasPublicModelsRequestModelsKeyValuePublic> productList) {
    this.productList = productList;
  }

  public OmegaAPIAreasPublicModelsRequestModelsAddProductListParametersRequest key(String key) {
    this.key = key;
    return this;
  }

   /**
   * Ключ доступа, строка
   * @return key
  **/
  @ApiModelProperty(required = true, value = "Ключ доступа, строка")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OmegaAPIAreasPublicModelsRequestModelsAddProductListParametersRequest omegaAPIAreasPublicModelsRequestModelsAddProductListParametersRequest = (OmegaAPIAreasPublicModelsRequestModelsAddProductListParametersRequest) o;
    return Objects.equals(this.productList, omegaAPIAreasPublicModelsRequestModelsAddProductListParametersRequest.productList) &&
        Objects.equals(this.key, omegaAPIAreasPublicModelsRequestModelsAddProductListParametersRequest.key);
  }

  @Override
  public int hashCode() {
    return Objects.hash(productList, key);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OmegaAPIAreasPublicModelsRequestModelsAddProductListParametersRequest {\n");
    
    sb.append("    productList: ").append(toIndentedString(productList)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

