/*
 * Omega.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.OmegaAPIAreasEnterpriseOmegaModelsDocumentsClaimClaimProductModel;
import io.swagger.client.model.OmegaAPIAreasEnterpriseOmegaModelsDocumentsClaimDocumentReason;
import io.swagger.client.model.OmegaAPIAreasEnterpriseOmegaModelsRefKeyDescription;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * OmegaAPIAreasPublicModelsClaimPublicClaimData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-12-27T17:23:48.058+02:00")
public class OmegaAPIAreasPublicModelsClaimPublicClaimData {
  @SerializedName("ClaimID")
  private String claimID = null;

  @SerializedName("Number")
  private String number = null;

  @SerializedName("StatusID")
  private String statusID = null;

  @SerializedName("Status")
  private String status = null;

  @SerializedName("FDate")
  private String fdate = null;

  @SerializedName("Sum")
  private Double sum = null;

  @SerializedName("Basic")
  private OmegaAPIAreasEnterpriseOmegaModelsDocumentsClaimDocumentReason basic = null;

  @SerializedName("CommentDoc")
  private String commentDoc = null;

  @SerializedName("DocType")
  private OmegaAPIAreasEnterpriseOmegaModelsRefKeyDescription docType = null;

  @SerializedName("Contractor")
  private OmegaAPIAreasEnterpriseOmegaModelsRefKeyDescription contractor = null;

  @SerializedName("IsExpanded")
  private Boolean isExpanded = null;

  @SerializedName("Posted")
  private Boolean posted = null;

  @SerializedName("DeletionMark")
  private Boolean deletionMark = null;

  @SerializedName("ShipmentTypeID")
  private String shipmentTypeID = null;

  @SerializedName("ShipmentType")
  private String shipmentType = null;

  @SerializedName("AddressDetail")
  private OmegaAPIAreasEnterpriseOmegaModelsRefKeyDescription addressDetail = null;

  @SerializedName("Products")
  private List<OmegaAPIAreasEnterpriseOmegaModelsDocumentsClaimClaimProductModel> products = null;

  @SerializedName("Accepted")
  private Boolean accepted = null;

  @SerializedName("ClaimID77")
  private String claimID77 = null;

  @SerializedName("Manager")
  private OmegaAPIAreasEnterpriseOmegaModelsRefKeyDescription manager = null;

  @SerializedName("Weight")
  private Double weight = null;

  @SerializedName("SumDiscount")
  private Double sumDiscount = null;

  public OmegaAPIAreasPublicModelsClaimPublicClaimData claimID(String claimID) {
    this.claimID = claimID;
    return this;
  }

   /**
   * Get claimID
   * @return claimID
  **/
  @ApiModelProperty(value = "")
  public String getClaimID() {
    return claimID;
  }

  public void setClaimID(String claimID) {
    this.claimID = claimID;
  }

  public OmegaAPIAreasPublicModelsClaimPublicClaimData number(String number) {
    this.number = number;
    return this;
  }

   /**
   * Get number
   * @return number
  **/
  @ApiModelProperty(value = "")
  public String getNumber() {
    return number;
  }

  public void setNumber(String number) {
    this.number = number;
  }

  public OmegaAPIAreasPublicModelsClaimPublicClaimData statusID(String statusID) {
    this.statusID = statusID;
    return this;
  }

   /**
   * Get statusID
   * @return statusID
  **/
  @ApiModelProperty(value = "")
  public String getStatusID() {
    return statusID;
  }

  public void setStatusID(String statusID) {
    this.statusID = statusID;
  }

  public OmegaAPIAreasPublicModelsClaimPublicClaimData status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public OmegaAPIAreasPublicModelsClaimPublicClaimData fdate(String fdate) {
    this.fdate = fdate;
    return this;
  }

   /**
   * Get fdate
   * @return fdate
  **/
  @ApiModelProperty(value = "")
  public String getFdate() {
    return fdate;
  }

  public void setFdate(String fdate) {
    this.fdate = fdate;
  }

  public OmegaAPIAreasPublicModelsClaimPublicClaimData sum(Double sum) {
    this.sum = sum;
    return this;
  }

   /**
   * Get sum
   * @return sum
  **/
  @ApiModelProperty(value = "")
  public Double getSum() {
    return sum;
  }

  public void setSum(Double sum) {
    this.sum = sum;
  }

  public OmegaAPIAreasPublicModelsClaimPublicClaimData basic(OmegaAPIAreasEnterpriseOmegaModelsDocumentsClaimDocumentReason basic) {
    this.basic = basic;
    return this;
  }

   /**
   * Get basic
   * @return basic
  **/
  @ApiModelProperty(value = "")
  public OmegaAPIAreasEnterpriseOmegaModelsDocumentsClaimDocumentReason getBasic() {
    return basic;
  }

  public void setBasic(OmegaAPIAreasEnterpriseOmegaModelsDocumentsClaimDocumentReason basic) {
    this.basic = basic;
  }

  public OmegaAPIAreasPublicModelsClaimPublicClaimData commentDoc(String commentDoc) {
    this.commentDoc = commentDoc;
    return this;
  }

   /**
   * Get commentDoc
   * @return commentDoc
  **/
  @ApiModelProperty(value = "")
  public String getCommentDoc() {
    return commentDoc;
  }

  public void setCommentDoc(String commentDoc) {
    this.commentDoc = commentDoc;
  }

  public OmegaAPIAreasPublicModelsClaimPublicClaimData docType(OmegaAPIAreasEnterpriseOmegaModelsRefKeyDescription docType) {
    this.docType = docType;
    return this;
  }

   /**
   * Get docType
   * @return docType
  **/
  @ApiModelProperty(value = "")
  public OmegaAPIAreasEnterpriseOmegaModelsRefKeyDescription getDocType() {
    return docType;
  }

  public void setDocType(OmegaAPIAreasEnterpriseOmegaModelsRefKeyDescription docType) {
    this.docType = docType;
  }

  public OmegaAPIAreasPublicModelsClaimPublicClaimData contractor(OmegaAPIAreasEnterpriseOmegaModelsRefKeyDescription contractor) {
    this.contractor = contractor;
    return this;
  }

   /**
   * Get contractor
   * @return contractor
  **/
  @ApiModelProperty(value = "")
  public OmegaAPIAreasEnterpriseOmegaModelsRefKeyDescription getContractor() {
    return contractor;
  }

  public void setContractor(OmegaAPIAreasEnterpriseOmegaModelsRefKeyDescription contractor) {
    this.contractor = contractor;
  }

  public OmegaAPIAreasPublicModelsClaimPublicClaimData isExpanded(Boolean isExpanded) {
    this.isExpanded = isExpanded;
    return this;
  }

   /**
   * Get isExpanded
   * @return isExpanded
  **/
  @ApiModelProperty(value = "")
  public Boolean getIsExpanded() {
    return isExpanded;
  }

  public void setIsExpanded(Boolean isExpanded) {
    this.isExpanded = isExpanded;
  }

  public OmegaAPIAreasPublicModelsClaimPublicClaimData posted(Boolean posted) {
    this.posted = posted;
    return this;
  }

   /**
   * Get posted
   * @return posted
  **/
  @ApiModelProperty(value = "")
  public Boolean getPosted() {
    return posted;
  }

  public void setPosted(Boolean posted) {
    this.posted = posted;
  }

  public OmegaAPIAreasPublicModelsClaimPublicClaimData deletionMark(Boolean deletionMark) {
    this.deletionMark = deletionMark;
    return this;
  }

   /**
   * Get deletionMark
   * @return deletionMark
  **/
  @ApiModelProperty(value = "")
  public Boolean getDeletionMark() {
    return deletionMark;
  }

  public void setDeletionMark(Boolean deletionMark) {
    this.deletionMark = deletionMark;
  }

  public OmegaAPIAreasPublicModelsClaimPublicClaimData shipmentTypeID(String shipmentTypeID) {
    this.shipmentTypeID = shipmentTypeID;
    return this;
  }

   /**
   * Get shipmentTypeID
   * @return shipmentTypeID
  **/
  @ApiModelProperty(value = "")
  public String getShipmentTypeID() {
    return shipmentTypeID;
  }

  public void setShipmentTypeID(String shipmentTypeID) {
    this.shipmentTypeID = shipmentTypeID;
  }

  public OmegaAPIAreasPublicModelsClaimPublicClaimData shipmentType(String shipmentType) {
    this.shipmentType = shipmentType;
    return this;
  }

   /**
   * Get shipmentType
   * @return shipmentType
  **/
  @ApiModelProperty(value = "")
  public String getShipmentType() {
    return shipmentType;
  }

  public void setShipmentType(String shipmentType) {
    this.shipmentType = shipmentType;
  }

  public OmegaAPIAreasPublicModelsClaimPublicClaimData addressDetail(OmegaAPIAreasEnterpriseOmegaModelsRefKeyDescription addressDetail) {
    this.addressDetail = addressDetail;
    return this;
  }

   /**
   * Get addressDetail
   * @return addressDetail
  **/
  @ApiModelProperty(value = "")
  public OmegaAPIAreasEnterpriseOmegaModelsRefKeyDescription getAddressDetail() {
    return addressDetail;
  }

  public void setAddressDetail(OmegaAPIAreasEnterpriseOmegaModelsRefKeyDescription addressDetail) {
    this.addressDetail = addressDetail;
  }

  public OmegaAPIAreasPublicModelsClaimPublicClaimData products(List<OmegaAPIAreasEnterpriseOmegaModelsDocumentsClaimClaimProductModel> products) {
    this.products = products;
    return this;
  }

  public OmegaAPIAreasPublicModelsClaimPublicClaimData addProductsItem(OmegaAPIAreasEnterpriseOmegaModelsDocumentsClaimClaimProductModel productsItem) {
    if (this.products == null) {
      this.products = new ArrayList<OmegaAPIAreasEnterpriseOmegaModelsDocumentsClaimClaimProductModel>();
    }
    this.products.add(productsItem);
    return this;
  }

   /**
   * Get products
   * @return products
  **/
  @ApiModelProperty(value = "")
  public List<OmegaAPIAreasEnterpriseOmegaModelsDocumentsClaimClaimProductModel> getProducts() {
    return products;
  }

  public void setProducts(List<OmegaAPIAreasEnterpriseOmegaModelsDocumentsClaimClaimProductModel> products) {
    this.products = products;
  }

  public OmegaAPIAreasPublicModelsClaimPublicClaimData accepted(Boolean accepted) {
    this.accepted = accepted;
    return this;
  }

   /**
   * Get accepted
   * @return accepted
  **/
  @ApiModelProperty(value = "")
  public Boolean getAccepted() {
    return accepted;
  }

  public void setAccepted(Boolean accepted) {
    this.accepted = accepted;
  }

  public OmegaAPIAreasPublicModelsClaimPublicClaimData claimID77(String claimID77) {
    this.claimID77 = claimID77;
    return this;
  }

   /**
   * Get claimID77
   * @return claimID77
  **/
  @ApiModelProperty(value = "")
  public String getClaimID77() {
    return claimID77;
  }

  public void setClaimID77(String claimID77) {
    this.claimID77 = claimID77;
  }

  public OmegaAPIAreasPublicModelsClaimPublicClaimData manager(OmegaAPIAreasEnterpriseOmegaModelsRefKeyDescription manager) {
    this.manager = manager;
    return this;
  }

   /**
   * Get manager
   * @return manager
  **/
  @ApiModelProperty(value = "")
  public OmegaAPIAreasEnterpriseOmegaModelsRefKeyDescription getManager() {
    return manager;
  }

  public void setManager(OmegaAPIAreasEnterpriseOmegaModelsRefKeyDescription manager) {
    this.manager = manager;
  }

  public OmegaAPIAreasPublicModelsClaimPublicClaimData weight(Double weight) {
    this.weight = weight;
    return this;
  }

   /**
   * Get weight
   * @return weight
  **/
  @ApiModelProperty(value = "")
  public Double getWeight() {
    return weight;
  }

  public void setWeight(Double weight) {
    this.weight = weight;
  }

  public OmegaAPIAreasPublicModelsClaimPublicClaimData sumDiscount(Double sumDiscount) {
    this.sumDiscount = sumDiscount;
    return this;
  }

   /**
   * Get sumDiscount
   * @return sumDiscount
  **/
  @ApiModelProperty(value = "")
  public Double getSumDiscount() {
    return sumDiscount;
  }

  public void setSumDiscount(Double sumDiscount) {
    this.sumDiscount = sumDiscount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OmegaAPIAreasPublicModelsClaimPublicClaimData omegaAPIAreasPublicModelsClaimPublicClaimData = (OmegaAPIAreasPublicModelsClaimPublicClaimData) o;
    return Objects.equals(this.claimID, omegaAPIAreasPublicModelsClaimPublicClaimData.claimID) &&
        Objects.equals(this.number, omegaAPIAreasPublicModelsClaimPublicClaimData.number) &&
        Objects.equals(this.statusID, omegaAPIAreasPublicModelsClaimPublicClaimData.statusID) &&
        Objects.equals(this.status, omegaAPIAreasPublicModelsClaimPublicClaimData.status) &&
        Objects.equals(this.fdate, omegaAPIAreasPublicModelsClaimPublicClaimData.fdate) &&
        Objects.equals(this.sum, omegaAPIAreasPublicModelsClaimPublicClaimData.sum) &&
        Objects.equals(this.basic, omegaAPIAreasPublicModelsClaimPublicClaimData.basic) &&
        Objects.equals(this.commentDoc, omegaAPIAreasPublicModelsClaimPublicClaimData.commentDoc) &&
        Objects.equals(this.docType, omegaAPIAreasPublicModelsClaimPublicClaimData.docType) &&
        Objects.equals(this.contractor, omegaAPIAreasPublicModelsClaimPublicClaimData.contractor) &&
        Objects.equals(this.isExpanded, omegaAPIAreasPublicModelsClaimPublicClaimData.isExpanded) &&
        Objects.equals(this.posted, omegaAPIAreasPublicModelsClaimPublicClaimData.posted) &&
        Objects.equals(this.deletionMark, omegaAPIAreasPublicModelsClaimPublicClaimData.deletionMark) &&
        Objects.equals(this.shipmentTypeID, omegaAPIAreasPublicModelsClaimPublicClaimData.shipmentTypeID) &&
        Objects.equals(this.shipmentType, omegaAPIAreasPublicModelsClaimPublicClaimData.shipmentType) &&
        Objects.equals(this.addressDetail, omegaAPIAreasPublicModelsClaimPublicClaimData.addressDetail) &&
        Objects.equals(this.products, omegaAPIAreasPublicModelsClaimPublicClaimData.products) &&
        Objects.equals(this.accepted, omegaAPIAreasPublicModelsClaimPublicClaimData.accepted) &&
        Objects.equals(this.claimID77, omegaAPIAreasPublicModelsClaimPublicClaimData.claimID77) &&
        Objects.equals(this.manager, omegaAPIAreasPublicModelsClaimPublicClaimData.manager) &&
        Objects.equals(this.weight, omegaAPIAreasPublicModelsClaimPublicClaimData.weight) &&
        Objects.equals(this.sumDiscount, omegaAPIAreasPublicModelsClaimPublicClaimData.sumDiscount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(claimID, number, statusID, status, fdate, sum, basic, commentDoc, docType, contractor, isExpanded, posted, deletionMark, shipmentTypeID, shipmentType, addressDetail, products, accepted, claimID77, manager, weight, sumDiscount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OmegaAPIAreasPublicModelsClaimPublicClaimData {\n");
    
    sb.append("    claimID: ").append(toIndentedString(claimID)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    statusID: ").append(toIndentedString(statusID)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    fdate: ").append(toIndentedString(fdate)).append("\n");
    sb.append("    sum: ").append(toIndentedString(sum)).append("\n");
    sb.append("    basic: ").append(toIndentedString(basic)).append("\n");
    sb.append("    commentDoc: ").append(toIndentedString(commentDoc)).append("\n");
    sb.append("    docType: ").append(toIndentedString(docType)).append("\n");
    sb.append("    contractor: ").append(toIndentedString(contractor)).append("\n");
    sb.append("    isExpanded: ").append(toIndentedString(isExpanded)).append("\n");
    sb.append("    posted: ").append(toIndentedString(posted)).append("\n");
    sb.append("    deletionMark: ").append(toIndentedString(deletionMark)).append("\n");
    sb.append("    shipmentTypeID: ").append(toIndentedString(shipmentTypeID)).append("\n");
    sb.append("    shipmentType: ").append(toIndentedString(shipmentType)).append("\n");
    sb.append("    addressDetail: ").append(toIndentedString(addressDetail)).append("\n");
    sb.append("    products: ").append(toIndentedString(products)).append("\n");
    sb.append("    accepted: ").append(toIndentedString(accepted)).append("\n");
    sb.append("    claimID77: ").append(toIndentedString(claimID77)).append("\n");
    sb.append("    manager: ").append(toIndentedString(manager)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("    sumDiscount: ").append(toIndentedString(sumDiscount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

