/*
 * Omega.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * OmegaAPIAreasEnterpriseOmegaModelsRefKeyDescription
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-12-27T17:23:48.058+02:00")
public class OmegaAPIAreasEnterpriseOmegaModelsRefKeyDescription {
  @SerializedName("Ref_Key")
  private String refKey = null;

  @SerializedName("Description")
  private String description = null;

  public OmegaAPIAreasEnterpriseOmegaModelsRefKeyDescription refKey(String refKey) {
    this.refKey = refKey;
    return this;
  }

   /**
   * Get refKey
   * @return refKey
  **/
  @ApiModelProperty(value = "")
  public String getRefKey() {
    return refKey;
  }

  public void setRefKey(String refKey) {
    this.refKey = refKey;
  }

  public OmegaAPIAreasEnterpriseOmegaModelsRefKeyDescription description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OmegaAPIAreasEnterpriseOmegaModelsRefKeyDescription omegaAPIAreasEnterpriseOmegaModelsRefKeyDescription = (OmegaAPIAreasEnterpriseOmegaModelsRefKeyDescription) o;
    return Objects.equals(this.refKey, omegaAPIAreasEnterpriseOmegaModelsRefKeyDescription.refKey) &&
        Objects.equals(this.description, omegaAPIAreasEnterpriseOmegaModelsRefKeyDescription.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(refKey, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OmegaAPIAreasEnterpriseOmegaModelsRefKeyDescription {\n");
    
    sb.append("    refKey: ").append(toIndentedString(refKey)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

