/*
 * Omega.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * OmegaAPIAreasPublicModelsRequestModelsSearchGetProductImageParametersRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-12-27T17:23:48.058+02:00")
public class OmegaAPIAreasPublicModelsRequestModelsSearchGetProductImageParametersRequest {
  @SerializedName("ProductId")
  private Long productId = null;

  @SerializedName("Number")
  private Integer number = null;

  @SerializedName("Key")
  private String key = null;

  public OmegaAPIAreasPublicModelsRequestModelsSearchGetProductImageParametersRequest productId(Long productId) {
    this.productId = productId;
    return this;
  }

   /**
   * Уникальный идентификатор товара
   * @return productId
  **/
  @ApiModelProperty(required = true, value = "Уникальный идентификатор товара")
  public Long getProductId() {
    return productId;
  }

  public void setProductId(Long productId) {
    this.productId = productId;
  }

  public OmegaAPIAreasPublicModelsRequestModelsSearchGetProductImageParametersRequest number(Integer number) {
    this.number = number;
    return this;
  }

   /**
   * Номер фото
   * @return number
  **/
  @ApiModelProperty(required = true, value = "Номер фото")
  public Integer getNumber() {
    return number;
  }

  public void setNumber(Integer number) {
    this.number = number;
  }

  public OmegaAPIAreasPublicModelsRequestModelsSearchGetProductImageParametersRequest key(String key) {
    this.key = key;
    return this;
  }

   /**
   * Ключ доступа, строка
   * @return key
  **/
  @ApiModelProperty(required = true, value = "Ключ доступа, строка")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OmegaAPIAreasPublicModelsRequestModelsSearchGetProductImageParametersRequest omegaAPIAreasPublicModelsRequestModelsSearchGetProductImageParametersRequest = (OmegaAPIAreasPublicModelsRequestModelsSearchGetProductImageParametersRequest) o;
    return Objects.equals(this.productId, omegaAPIAreasPublicModelsRequestModelsSearchGetProductImageParametersRequest.productId) &&
        Objects.equals(this.number, omegaAPIAreasPublicModelsRequestModelsSearchGetProductImageParametersRequest.number) &&
        Objects.equals(this.key, omegaAPIAreasPublicModelsRequestModelsSearchGetProductImageParametersRequest.key);
  }

  @Override
  public int hashCode() {
    return Objects.hash(productId, number, key);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OmegaAPIAreasPublicModelsRequestModelsSearchGetProductImageParametersRequest {\n");
    
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

