/*
 * Omega.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.OmegaAPIAreasPublicModelsInvoiceSettingsShipmentSelfDeliveryPublicPaidType;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * OmegaAPIAreasPublicModelsInvoiceSettingsShipmentSelfDeliveryPublicSelfDeliveryShipmentSettings
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-12-27T17:23:48.058+02:00")
public class OmegaAPIAreasPublicModelsInvoiceSettingsShipmentSelfDeliveryPublicSelfDeliveryShipmentSettings {
  @SerializedName("ShipmentType")
  private String shipmentType = null;

  @SerializedName("PaidTypes")
  private List<OmegaAPIAreasPublicModelsInvoiceSettingsShipmentSelfDeliveryPublicPaidType> paidTypes = null;

  public OmegaAPIAreasPublicModelsInvoiceSettingsShipmentSelfDeliveryPublicSelfDeliveryShipmentSettings shipmentType(String shipmentType) {
    this.shipmentType = shipmentType;
    return this;
  }

   /**
   * Уникальный идентификатор вида доставки, строка
   * @return shipmentType
  **/
  @ApiModelProperty(value = "Уникальный идентификатор вида доставки, строка")
  public String getShipmentType() {
    return shipmentType;
  }

  public void setShipmentType(String shipmentType) {
    this.shipmentType = shipmentType;
  }

  public OmegaAPIAreasPublicModelsInvoiceSettingsShipmentSelfDeliveryPublicSelfDeliveryShipmentSettings paidTypes(List<OmegaAPIAreasPublicModelsInvoiceSettingsShipmentSelfDeliveryPublicPaidType> paidTypes) {
    this.paidTypes = paidTypes;
    return this;
  }

  public OmegaAPIAreasPublicModelsInvoiceSettingsShipmentSelfDeliveryPublicSelfDeliveryShipmentSettings addPaidTypesItem(OmegaAPIAreasPublicModelsInvoiceSettingsShipmentSelfDeliveryPublicPaidType paidTypesItem) {
    if (this.paidTypes == null) {
      this.paidTypes = new ArrayList<OmegaAPIAreasPublicModelsInvoiceSettingsShipmentSelfDeliveryPublicPaidType>();
    }
    this.paidTypes.add(paidTypesItem);
    return this;
  }

   /**
   * Get paidTypes
   * @return paidTypes
  **/
  @ApiModelProperty(value = "")
  public List<OmegaAPIAreasPublicModelsInvoiceSettingsShipmentSelfDeliveryPublicPaidType> getPaidTypes() {
    return paidTypes;
  }

  public void setPaidTypes(List<OmegaAPIAreasPublicModelsInvoiceSettingsShipmentSelfDeliveryPublicPaidType> paidTypes) {
    this.paidTypes = paidTypes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OmegaAPIAreasPublicModelsInvoiceSettingsShipmentSelfDeliveryPublicSelfDeliveryShipmentSettings omegaAPIAreasPublicModelsInvoiceSettingsShipmentSelfDeliveryPublicSelfDeliveryShipmentSettings = (OmegaAPIAreasPublicModelsInvoiceSettingsShipmentSelfDeliveryPublicSelfDeliveryShipmentSettings) o;
    return Objects.equals(this.shipmentType, omegaAPIAreasPublicModelsInvoiceSettingsShipmentSelfDeliveryPublicSelfDeliveryShipmentSettings.shipmentType) &&
        Objects.equals(this.paidTypes, omegaAPIAreasPublicModelsInvoiceSettingsShipmentSelfDeliveryPublicSelfDeliveryShipmentSettings.paidTypes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shipmentType, paidTypes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OmegaAPIAreasPublicModelsInvoiceSettingsShipmentSelfDeliveryPublicSelfDeliveryShipmentSettings {\n");
    
    sb.append("    shipmentType: ").append(toIndentedString(shipmentType)).append("\n");
    sb.append("    paidTypes: ").append(toIndentedString(paidTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

