/*
 * Omega.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.OmegaAPIModelsApplicabilityItem;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * OmegaAPIModelsApplicabilityItem
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-12-27T17:23:48.058+02:00")
public class OmegaAPIModelsApplicabilityItem {
  @SerializedName("Id")
  private String id = null;

  @SerializedName("Name")
  private String name = null;

  @SerializedName("Children")
  private List<OmegaAPIModelsApplicabilityItem> children = null;

  public OmegaAPIModelsApplicabilityItem id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public OmegaAPIModelsApplicabilityItem name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public OmegaAPIModelsApplicabilityItem children(List<OmegaAPIModelsApplicabilityItem> children) {
    this.children = children;
    return this;
  }

  public OmegaAPIModelsApplicabilityItem addChildrenItem(OmegaAPIModelsApplicabilityItem childrenItem) {
    if (this.children == null) {
      this.children = new ArrayList<OmegaAPIModelsApplicabilityItem>();
    }
    this.children.add(childrenItem);
    return this;
  }

   /**
   * Get children
   * @return children
  **/
  @ApiModelProperty(value = "")
  public List<OmegaAPIModelsApplicabilityItem> getChildren() {
    return children;
  }

  public void setChildren(List<OmegaAPIModelsApplicabilityItem> children) {
    this.children = children;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OmegaAPIModelsApplicabilityItem omegaAPIModelsApplicabilityItem = (OmegaAPIModelsApplicabilityItem) o;
    return Objects.equals(this.id, omegaAPIModelsApplicabilityItem.id) &&
        Objects.equals(this.name, omegaAPIModelsApplicabilityItem.name) &&
        Objects.equals(this.children, omegaAPIModelsApplicabilityItem.children);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, children);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OmegaAPIModelsApplicabilityItem {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    children: ").append(toIndentedString(children)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

