/*
 * Omega.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * OmegaAPIAreasPublicModelsRequestModelsTreeGetTreeNodeParametersRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-12-27T17:23:48.058+02:00")
public class OmegaAPIAreasPublicModelsRequestModelsTreeGetTreeNodeParametersRequest {
  @SerializedName("ModificationId")
  private Integer modificationId = null;

  @SerializedName("NodeId")
  private Integer nodeId = null;

  @SerializedName("Key")
  private String key = null;

  public OmegaAPIAreasPublicModelsRequestModelsTreeGetTreeNodeParametersRequest modificationId(Integer modificationId) {
    this.modificationId = modificationId;
    return this;
  }

   /**
   * Уникальный идентификатор модификации автомобиля
   * @return modificationId
  **/
  @ApiModelProperty(required = true, value = "Уникальный идентификатор модификации автомобиля")
  public Integer getModificationId() {
    return modificationId;
  }

  public void setModificationId(Integer modificationId) {
    this.modificationId = modificationId;
  }

  public OmegaAPIAreasPublicModelsRequestModelsTreeGetTreeNodeParametersRequest nodeId(Integer nodeId) {
    this.nodeId = nodeId;
    return this;
  }

   /**
   * Идентификатор родительской ноды, если задан идентификатор - возвращает его ближайшее вложение, если задан null или 200000000 возвращает первый уровень
   * @return nodeId
  **/
  @ApiModelProperty(value = "Идентификатор родительской ноды, если задан идентификатор - возвращает его ближайшее вложение, если задан null или 200000000 возвращает первый уровень")
  public Integer getNodeId() {
    return nodeId;
  }

  public void setNodeId(Integer nodeId) {
    this.nodeId = nodeId;
  }

  public OmegaAPIAreasPublicModelsRequestModelsTreeGetTreeNodeParametersRequest key(String key) {
    this.key = key;
    return this;
  }

   /**
   * Ключ доступа, строка
   * @return key
  **/
  @ApiModelProperty(required = true, value = "Ключ доступа, строка")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OmegaAPIAreasPublicModelsRequestModelsTreeGetTreeNodeParametersRequest omegaAPIAreasPublicModelsRequestModelsTreeGetTreeNodeParametersRequest = (OmegaAPIAreasPublicModelsRequestModelsTreeGetTreeNodeParametersRequest) o;
    return Objects.equals(this.modificationId, omegaAPIAreasPublicModelsRequestModelsTreeGetTreeNodeParametersRequest.modificationId) &&
        Objects.equals(this.nodeId, omegaAPIAreasPublicModelsRequestModelsTreeGetTreeNodeParametersRequest.nodeId) &&
        Objects.equals(this.key, omegaAPIAreasPublicModelsRequestModelsTreeGetTreeNodeParametersRequest.key);
  }

  @Override
  public int hashCode() {
    return Objects.hash(modificationId, nodeId, key);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OmegaAPIAreasPublicModelsRequestModelsTreeGetTreeNodeParametersRequest {\n");
    
    sb.append("    modificationId: ").append(toIndentedString(modificationId)).append("\n");
    sb.append("    nodeId: ").append(toIndentedString(nodeId)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

