/*
 * Omega.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierPublicDeliveryServiceType
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-12-27T17:23:48.058+02:00")
public class OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierPublicDeliveryServiceType {
  @SerializedName("Name")
  private String name = null;

  @SerializedName("ServiceTypeId")
  private String serviceTypeId = null;

  public OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierPublicDeliveryServiceType name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Наименование сервиса курьерской доставки, строка
   * @return name
  **/
  @ApiModelProperty(value = "Наименование сервиса курьерской доставки, строка")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierPublicDeliveryServiceType serviceTypeId(String serviceTypeId) {
    this.serviceTypeId = serviceTypeId;
    return this;
  }

   /**
   * Уникальный идентификатор сервиса курьерской доставки, строка
   * @return serviceTypeId
  **/
  @ApiModelProperty(value = "Уникальный идентификатор сервиса курьерской доставки, строка")
  public String getServiceTypeId() {
    return serviceTypeId;
  }

  public void setServiceTypeId(String serviceTypeId) {
    this.serviceTypeId = serviceTypeId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierPublicDeliveryServiceType omegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierPublicDeliveryServiceType = (OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierPublicDeliveryServiceType) o;
    return Objects.equals(this.name, omegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierPublicDeliveryServiceType.name) &&
        Objects.equals(this.serviceTypeId, omegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierPublicDeliveryServiceType.serviceTypeId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, serviceTypeId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierPublicDeliveryServiceType {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    serviceTypeId: ").append(toIndentedString(serviceTypeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

