/*
 * Omega.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.OmegaAPIAreasPublicModelsPublicExpenseModel;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * OmegaAPIAreasPublicModelsPublicSearchResultOmegaAPIAreasEnterpriseOmegaModelsDocumentsExpenseExpenseOmegaAPIAreasPublicModelsPublicExpenseModel
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-12-27T17:23:48.058+02:00")
public class OmegaAPIAreasPublicModelsPublicSearchResultOmegaAPIAreasEnterpriseOmegaModelsDocumentsExpenseExpenseOmegaAPIAreasPublicModelsPublicExpenseModel {
  @SerializedName("Result")
  private List<OmegaAPIAreasPublicModelsPublicExpenseModel> result = null;

  @SerializedName("Total")
  private Long total = null;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    NUMBER_0(0),
    
    NUMBER_1(1),
    
    NUMBER_2(2),
    
    NUMBER_3(3);

    private Integer value;

    StatusEnum(Integer value) {
      this.value = value;
    }

    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        Integer value = jsonReader.nextInt();
        return StatusEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("Status")
  private StatusEnum status = null;

  public OmegaAPIAreasPublicModelsPublicSearchResultOmegaAPIAreasEnterpriseOmegaModelsDocumentsExpenseExpenseOmegaAPIAreasPublicModelsPublicExpenseModel result(List<OmegaAPIAreasPublicModelsPublicExpenseModel> result) {
    this.result = result;
    return this;
  }

  public OmegaAPIAreasPublicModelsPublicSearchResultOmegaAPIAreasEnterpriseOmegaModelsDocumentsExpenseExpenseOmegaAPIAreasPublicModelsPublicExpenseModel addResultItem(OmegaAPIAreasPublicModelsPublicExpenseModel resultItem) {
    if (this.result == null) {
      this.result = new ArrayList<OmegaAPIAreasPublicModelsPublicExpenseModel>();
    }
    this.result.add(resultItem);
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @ApiModelProperty(value = "")
  public List<OmegaAPIAreasPublicModelsPublicExpenseModel> getResult() {
    return result;
  }

  public void setResult(List<OmegaAPIAreasPublicModelsPublicExpenseModel> result) {
    this.result = result;
  }

  public OmegaAPIAreasPublicModelsPublicSearchResultOmegaAPIAreasEnterpriseOmegaModelsDocumentsExpenseExpenseOmegaAPIAreasPublicModelsPublicExpenseModel total(Long total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @ApiModelProperty(value = "")
  public Long getTotal() {
    return total;
  }

  public void setTotal(Long total) {
    this.total = total;
  }

  public OmegaAPIAreasPublicModelsPublicSearchResultOmegaAPIAreasEnterpriseOmegaModelsDocumentsExpenseExpenseOmegaAPIAreasPublicModelsPublicExpenseModel status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OmegaAPIAreasPublicModelsPublicSearchResultOmegaAPIAreasEnterpriseOmegaModelsDocumentsExpenseExpenseOmegaAPIAreasPublicModelsPublicExpenseModel omegaAPIAreasPublicModelsPublicSearchResultOmegaAPIAreasEnterpriseOmegaModelsDocumentsExpenseExpenseOmegaAPIAreasPublicModelsPublicExpenseModel = (OmegaAPIAreasPublicModelsPublicSearchResultOmegaAPIAreasEnterpriseOmegaModelsDocumentsExpenseExpenseOmegaAPIAreasPublicModelsPublicExpenseModel) o;
    return Objects.equals(this.result, omegaAPIAreasPublicModelsPublicSearchResultOmegaAPIAreasEnterpriseOmegaModelsDocumentsExpenseExpenseOmegaAPIAreasPublicModelsPublicExpenseModel.result) &&
        Objects.equals(this.total, omegaAPIAreasPublicModelsPublicSearchResultOmegaAPIAreasEnterpriseOmegaModelsDocumentsExpenseExpenseOmegaAPIAreasPublicModelsPublicExpenseModel.total) &&
        Objects.equals(this.status, omegaAPIAreasPublicModelsPublicSearchResultOmegaAPIAreasEnterpriseOmegaModelsDocumentsExpenseExpenseOmegaAPIAreasPublicModelsPublicExpenseModel.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(result, total, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OmegaAPIAreasPublicModelsPublicSearchResultOmegaAPIAreasEnterpriseOmegaModelsDocumentsExpenseExpenseOmegaAPIAreasPublicModelsPublicExpenseModel {\n");
    
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

