/*
 * Omega.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * OmegaAPIAreasPublicModelsGetAccountResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-12-27T17:23:48.058+02:00")
public class OmegaAPIAreasPublicModelsGetAccountResponse {
  @SerializedName("Key")
  private String key = null;

  @SerializedName("Host")
  private String host = null;

  @SerializedName("Ip")
  private String ip = null;

  @SerializedName("Access")
  private String access = null;

  @SerializedName("CustomerId")
  private String customerId = null;

  @SerializedName("Subscription")
  private String subscription = null;

  public OmegaAPIAreasPublicModelsGetAccountResponse key(String key) {
    this.key = key;
    return this;
  }

   /**
   * Ключ доступа
   * @return key
  **/
  @ApiModelProperty(value = "Ключ доступа")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public OmegaAPIAreasPublicModelsGetAccountResponse host(String host) {
    this.host = host;
    return this;
  }

   /**
   * Хост
   * @return host
  **/
  @ApiModelProperty(value = "Хост")
  public String getHost() {
    return host;
  }

  public void setHost(String host) {
    this.host = host;
  }

  public OmegaAPIAreasPublicModelsGetAccountResponse ip(String ip) {
    this.ip = ip;
    return this;
  }

   /**
   * Ip адрес
   * @return ip
  **/
  @ApiModelProperty(value = "Ip адрес")
  public String getIp() {
    return ip;
  }

  public void setIp(String ip) {
    this.ip = ip;
  }

  public OmegaAPIAreasPublicModelsGetAccountResponse access(String access) {
    this.access = access;
    return this;
  }

   /**
   * Вид доступа
   * @return access
  **/
  @ApiModelProperty(value = "Вид доступа")
  public String getAccess() {
    return access;
  }

  public void setAccess(String access) {
    this.access = access;
  }

  public OmegaAPIAreasPublicModelsGetAccountResponse customerId(String customerId) {
    this.customerId = customerId;
    return this;
  }

   /**
   * Уникальный идентификатор контрагента по овнеру
   * @return customerId
  **/
  @ApiModelProperty(value = "Уникальный идентификатор контрагента по овнеру")
  public String getCustomerId() {
    return customerId;
  }

  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }

  public OmegaAPIAreasPublicModelsGetAccountResponse subscription(String subscription) {
    this.subscription = subscription;
    return this;
  }

   /**
   * Вид подписки
   * @return subscription
  **/
  @ApiModelProperty(value = "Вид подписки")
  public String getSubscription() {
    return subscription;
  }

  public void setSubscription(String subscription) {
    this.subscription = subscription;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OmegaAPIAreasPublicModelsGetAccountResponse omegaAPIAreasPublicModelsGetAccountResponse = (OmegaAPIAreasPublicModelsGetAccountResponse) o;
    return Objects.equals(this.key, omegaAPIAreasPublicModelsGetAccountResponse.key) &&
        Objects.equals(this.host, omegaAPIAreasPublicModelsGetAccountResponse.host) &&
        Objects.equals(this.ip, omegaAPIAreasPublicModelsGetAccountResponse.ip) &&
        Objects.equals(this.access, omegaAPIAreasPublicModelsGetAccountResponse.access) &&
        Objects.equals(this.customerId, omegaAPIAreasPublicModelsGetAccountResponse.customerId) &&
        Objects.equals(this.subscription, omegaAPIAreasPublicModelsGetAccountResponse.subscription);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, host, ip, access, customerId, subscription);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OmegaAPIAreasPublicModelsGetAccountResponse {\n");
    
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    host: ").append(toIndentedString(host)).append("\n");
    sb.append("    ip: ").append(toIndentedString(ip)).append("\n");
    sb.append("    access: ").append(toIndentedString(access)).append("\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    subscription: ").append(toIndentedString(subscription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

