/*
 * Omega.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * OmegaAPIAreasPublicModelsRequestModelsClaimPublicPhotoFile
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-12-27T17:23:48.058+02:00")
public class OmegaAPIAreasPublicModelsRequestModelsClaimPublicPhotoFile {
  @SerializedName("ProductId")
  private Long productId = null;

  @SerializedName("Data")
  private String data = null;

  @SerializedName("FileName")
  private String fileName = null;

  public OmegaAPIAreasPublicModelsRequestModelsClaimPublicPhotoFile productId(Long productId) {
    this.productId = productId;
    return this;
  }

   /**
   * Уникальный идентификатор товара, строка
   * @return productId
  **/
  @ApiModelProperty(required = true, value = "Уникальный идентификатор товара, строка")
  public Long getProductId() {
    return productId;
  }

  public void setProductId(Long productId) {
    this.productId = productId;
  }

  public OmegaAPIAreasPublicModelsRequestModelsClaimPublicPhotoFile data(String data) {
    this.data = data;
    return this;
  }

   /**
   * Изображение закодированное в base64, строка
   * @return data
  **/
  @ApiModelProperty(required = true, value = "Изображение закодированное в base64, строка")
  public String getData() {
    return data;
  }

  public void setData(String data) {
    this.data = data;
  }

  public OmegaAPIAreasPublicModelsRequestModelsClaimPublicPhotoFile fileName(String fileName) {
    this.fileName = fileName;
    return this;
  }

   /**
   * Имя файла, строка (test.jpg)
   * @return fileName
  **/
  @ApiModelProperty(required = true, value = "Имя файла, строка (test.jpg)")
  public String getFileName() {
    return fileName;
  }

  public void setFileName(String fileName) {
    this.fileName = fileName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OmegaAPIAreasPublicModelsRequestModelsClaimPublicPhotoFile omegaAPIAreasPublicModelsRequestModelsClaimPublicPhotoFile = (OmegaAPIAreasPublicModelsRequestModelsClaimPublicPhotoFile) o;
    return Objects.equals(this.productId, omegaAPIAreasPublicModelsRequestModelsClaimPublicPhotoFile.productId) &&
        Objects.equals(this.data, omegaAPIAreasPublicModelsRequestModelsClaimPublicPhotoFile.data) &&
        Objects.equals(this.fileName, omegaAPIAreasPublicModelsRequestModelsClaimPublicPhotoFile.fileName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(productId, data, fileName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OmegaAPIAreasPublicModelsRequestModelsClaimPublicPhotoFile {\n");
    
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

