/*
 * Omega.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-12-27T17:23:48.058+02:00")
public class OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest {
  @SerializedName("IsSale")
  private Integer isSale = null;

  @SerializedName("Rest")
  private Integer rest = null;

  @SerializedName("Manufacturers")
  private List<Integer> manufacturers = null;

  @SerializedName("PurposeTF")
  private List<String> purposeTF = null;

  @SerializedName("ColorTF")
  private List<String> colorTF = null;

  @SerializedName("SeasonalityTF")
  private List<String> seasonalityTF = null;

  @SerializedName("SpecOEMTF")
  private List<String> specOEMTF = null;

  @SerializedName("ScopeTF")
  private List<String> scopeTF = null;

  @SerializedName("From")
  private Integer from = null;

  @SerializedName("Count")
  private Integer count = null;

  @SerializedName("FormFactor")
  private Integer formFactor = null;

  @SerializedName("Key")
  private String key = null;

  public OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest isSale(Integer isSale) {
    this.isSale = isSale;
    return this;
  }

   /**
   * Признак снижения цены, 0 -все товары, 1 - только товары со скидкой
   * @return isSale
  **/
  @ApiModelProperty(value = "Признак снижения цены, 0 -все товары, 1 - только товары со скидкой")
  public Integer getIsSale() {
    return isSale;
  }

  public void setIsSale(Integer isSale) {
    this.isSale = isSale;
  }

  public OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest rest(Integer rest) {
    this.rest = rest;
    return this;
  }

   /**
   * Признак наличия товара на остатках, число, 0 - без учета остатков, 1 - только в наличии
   * @return rest
  **/
  @ApiModelProperty(value = "Признак наличия товара на остатках, число, 0 - без учета остатков, 1 - только в наличии")
  public Integer getRest() {
    return rest;
  }

  public void setRest(Integer rest) {
    this.rest = rest;
  }

  public OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest manufacturers(List<Integer> manufacturers) {
    this.manufacturers = manufacturers;
    return this;
  }

  public OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest addManufacturersItem(Integer manufacturersItem) {
    if (this.manufacturers == null) {
      this.manufacturers = new ArrayList<Integer>();
    }
    this.manufacturers.add(manufacturersItem);
    return this;
  }

   /**
   * Бренд
   * @return manufacturers
  **/
  @ApiModelProperty(value = "Бренд")
  public List<Integer> getManufacturers() {
    return manufacturers;
  }

  public void setManufacturers(List<Integer> manufacturers) {
    this.manufacturers = manufacturers;
  }

  public OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest purposeTF(List<String> purposeTF) {
    this.purposeTF = purposeTF;
    return this;
  }

  public OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest addPurposeTFItem(String purposeTFItem) {
    if (this.purposeTF == null) {
      this.purposeTF = new ArrayList<String>();
    }
    this.purposeTF.add(purposeTFItem);
    return this;
  }

   /**
   * Назначение
   * @return purposeTF
  **/
  @ApiModelProperty(value = "Назначение")
  public List<String> getPurposeTF() {
    return purposeTF;
  }

  public void setPurposeTF(List<String> purposeTF) {
    this.purposeTF = purposeTF;
  }

  public OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest colorTF(List<String> colorTF) {
    this.colorTF = colorTF;
    return this;
  }

  public OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest addColorTFItem(String colorTFItem) {
    if (this.colorTF == null) {
      this.colorTF = new ArrayList<String>();
    }
    this.colorTF.add(colorTFItem);
    return this;
  }

   /**
   * Цвет
   * @return colorTF
  **/
  @ApiModelProperty(value = "Цвет")
  public List<String> getColorTF() {
    return colorTF;
  }

  public void setColorTF(List<String> colorTF) {
    this.colorTF = colorTF;
  }

  public OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest seasonalityTF(List<String> seasonalityTF) {
    this.seasonalityTF = seasonalityTF;
    return this;
  }

  public OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest addSeasonalityTFItem(String seasonalityTFItem) {
    if (this.seasonalityTF == null) {
      this.seasonalityTF = new ArrayList<String>();
    }
    this.seasonalityTF.add(seasonalityTFItem);
    return this;
  }

   /**
   * Сезонность
   * @return seasonalityTF
  **/
  @ApiModelProperty(value = "Сезонность")
  public List<String> getSeasonalityTF() {
    return seasonalityTF;
  }

  public void setSeasonalityTF(List<String> seasonalityTF) {
    this.seasonalityTF = seasonalityTF;
  }

  public OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest specOEMTF(List<String> specOEMTF) {
    this.specOEMTF = specOEMTF;
    return this;
  }

  public OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest addSpecOEMTFItem(String specOEMTFItem) {
    if (this.specOEMTF == null) {
      this.specOEMTF = new ArrayList<String>();
    }
    this.specOEMTF.add(specOEMTFItem);
    return this;
  }

   /**
   * Спецификация OEMTF
   * @return specOEMTF
  **/
  @ApiModelProperty(value = "Спецификация OEMTF")
  public List<String> getSpecOEMTF() {
    return specOEMTF;
  }

  public void setSpecOEMTF(List<String> specOEMTF) {
    this.specOEMTF = specOEMTF;
  }

  public OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest scopeTF(List<String> scopeTF) {
    this.scopeTF = scopeTF;
    return this;
  }

  public OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest addScopeTFItem(String scopeTFItem) {
    if (this.scopeTF == null) {
      this.scopeTF = new ArrayList<String>();
    }
    this.scopeTF.add(scopeTFItem);
    return this;
  }

   /**
   * Обьем
   * @return scopeTF
  **/
  @ApiModelProperty(value = "Обьем")
  public List<String> getScopeTF() {
    return scopeTF;
  }

  public void setScopeTF(List<String> scopeTF) {
    this.scopeTF = scopeTF;
  }

  public OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest from(Integer from) {
    this.from = from;
    return this;
  }

   /**
   * Номер с которого начинаются товары - для постраничного вывода, по умолчанию с 0
   * @return from
  **/
  @ApiModelProperty(value = "Номер с которого начинаются товары - для постраничного вывода, по умолчанию с 0")
  public Integer getFrom() {
    return from;
  }

  public void setFrom(Integer from) {
    this.from = from;
  }

  public OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Количество результатов на страницу, по-умолчанию 24
   * minimum: 1
   * maximum: 2147483647
   * @return count
  **/
  @ApiModelProperty(value = "Количество результатов на страницу, по-умолчанию 24")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest formFactor(Integer formFactor) {
    this.formFactor = formFactor;
    return this;
  }

   /**
   * Тип автомобиля, 0 - легковой, 1 - грузовой, 2 - все
   * @return formFactor
  **/
  @ApiModelProperty(value = "Тип автомобиля, 0 - легковой, 1 - грузовой, 2 - все")
  public Integer getFormFactor() {
    return formFactor;
  }

  public void setFormFactor(Integer formFactor) {
    this.formFactor = formFactor;
  }

  public OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest key(String key) {
    this.key = key;
    return this;
  }

   /**
   * Ключ доступа, строка
   * @return key
  **/
  @ApiModelProperty(required = true, value = "Ключ доступа, строка")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest omegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest = (OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest) o;
    return Objects.equals(this.isSale, omegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest.isSale) &&
        Objects.equals(this.rest, omegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest.rest) &&
        Objects.equals(this.manufacturers, omegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest.manufacturers) &&
        Objects.equals(this.purposeTF, omegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest.purposeTF) &&
        Objects.equals(this.colorTF, omegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest.colorTF) &&
        Objects.equals(this.seasonalityTF, omegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest.seasonalityTF) &&
        Objects.equals(this.specOEMTF, omegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest.specOEMTF) &&
        Objects.equals(this.scopeTF, omegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest.scopeTF) &&
        Objects.equals(this.from, omegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest.from) &&
        Objects.equals(this.count, omegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest.count) &&
        Objects.equals(this.formFactor, omegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest.formFactor) &&
        Objects.equals(this.key, omegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest.key);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isSale, rest, manufacturers, purposeTF, colorTF, seasonalityTF, specOEMTF, scopeTF, from, count, formFactor, key);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest {\n");
    
    sb.append("    isSale: ").append(toIndentedString(isSale)).append("\n");
    sb.append("    rest: ").append(toIndentedString(rest)).append("\n");
    sb.append("    manufacturers: ").append(toIndentedString(manufacturers)).append("\n");
    sb.append("    purposeTF: ").append(toIndentedString(purposeTF)).append("\n");
    sb.append("    colorTF: ").append(toIndentedString(colorTF)).append("\n");
    sb.append("    seasonalityTF: ").append(toIndentedString(seasonalityTF)).append("\n");
    sb.append("    specOEMTF: ").append(toIndentedString(specOEMTF)).append("\n");
    sb.append("    scopeTF: ").append(toIndentedString(scopeTF)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    formFactor: ").append(toIndentedString(formFactor)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

