/*
 * Omega.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * OmegaAPIAreasPublicModelsSearchPublicCrossModel
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-12-27T17:23:48.058+02:00")
public class OmegaAPIAreasPublicModelsSearchPublicCrossModel {
  @SerializedName("ProductId")
  private Long productId = null;

  @SerializedName("Code")
  private String code = null;

  @SerializedName("Brand")
  private String brand = null;

  @SerializedName("ReplacementType")
  private String replacementType = null;

  public OmegaAPIAreasPublicModelsSearchPublicCrossModel productId(Long productId) {
    this.productId = productId;
    return this;
  }

   /**
   * Идентификатор товара
   * @return productId
  **/
  @ApiModelProperty(value = "Идентификатор товара")
  public Long getProductId() {
    return productId;
  }

  public void setProductId(Long productId) {
    this.productId = productId;
  }

  public OmegaAPIAreasPublicModelsSearchPublicCrossModel code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Каталожный код
   * @return code
  **/
  @ApiModelProperty(value = "Каталожный код")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public OmegaAPIAreasPublicModelsSearchPublicCrossModel brand(String brand) {
    this.brand = brand;
    return this;
  }

   /**
   * Производитель
   * @return brand
  **/
  @ApiModelProperty(value = "Производитель")
  public String getBrand() {
    return brand;
  }

  public void setBrand(String brand) {
    this.brand = brand;
  }

  public OmegaAPIAreasPublicModelsSearchPublicCrossModel replacementType(String replacementType) {
    this.replacementType = replacementType;
    return this;
  }

   /**
   * Тип аналога
   * @return replacementType
  **/
  @ApiModelProperty(value = "Тип аналога")
  public String getReplacementType() {
    return replacementType;
  }

  public void setReplacementType(String replacementType) {
    this.replacementType = replacementType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OmegaAPIAreasPublicModelsSearchPublicCrossModel omegaAPIAreasPublicModelsSearchPublicCrossModel = (OmegaAPIAreasPublicModelsSearchPublicCrossModel) o;
    return Objects.equals(this.productId, omegaAPIAreasPublicModelsSearchPublicCrossModel.productId) &&
        Objects.equals(this.code, omegaAPIAreasPublicModelsSearchPublicCrossModel.code) &&
        Objects.equals(this.brand, omegaAPIAreasPublicModelsSearchPublicCrossModel.brand) &&
        Objects.equals(this.replacementType, omegaAPIAreasPublicModelsSearchPublicCrossModel.replacementType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(productId, code, brand, replacementType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OmegaAPIAreasPublicModelsSearchPublicCrossModel {\n");
    
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    brand: ").append(toIndentedString(brand)).append("\n");
    sb.append("    replacementType: ").append(toIndentedString(replacementType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

