/*
 * Omega.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * OmegaAPIAreasPublicModelsExpsenseAdvancedInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-12-27T17:23:48.058+02:00")
public class OmegaAPIAreasPublicModelsExpsenseAdvancedInfo {
  @SerializedName("ContractName")
  private String contractName = null;

  @SerializedName("CreditDepth")
  private String creditDepth = null;

  @SerializedName("Recepient")
  private String recepient = null;

  @SerializedName("AccountNumber")
  private String accountNumber = null;

  @SerializedName("Address")
  private String address = null;

  public OmegaAPIAreasPublicModelsExpsenseAdvancedInfo contractName(String contractName) {
    this.contractName = contractName;
    return this;
  }

   /**
   * Наименование контракта
   * @return contractName
  **/
  @ApiModelProperty(value = "Наименование контракта")
  public String getContractName() {
    return contractName;
  }

  public void setContractName(String contractName) {
    this.contractName = contractName;
  }

  public OmegaAPIAreasPublicModelsExpsenseAdvancedInfo creditDepth(String creditDepth) {
    this.creditDepth = creditDepth;
    return this;
  }

   /**
   * Глубина кредита
   * @return creditDepth
  **/
  @ApiModelProperty(value = "Глубина кредита")
  public String getCreditDepth() {
    return creditDepth;
  }

  public void setCreditDepth(String creditDepth) {
    this.creditDepth = creditDepth;
  }

  public OmegaAPIAreasPublicModelsExpsenseAdvancedInfo recepient(String recepient) {
    this.recepient = recepient;
    return this;
  }

   /**
   * Получатель
   * @return recepient
  **/
  @ApiModelProperty(value = "Получатель")
  public String getRecepient() {
    return recepient;
  }

  public void setRecepient(String recepient) {
    this.recepient = recepient;
  }

  public OmegaAPIAreasPublicModelsExpsenseAdvancedInfo accountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
    return this;
  }

   /**
   * Номер расчётного счёта
   * @return accountNumber
  **/
  @ApiModelProperty(value = "Номер расчётного счёта")
  public String getAccountNumber() {
    return accountNumber;
  }

  public void setAccountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
  }

  public OmegaAPIAreasPublicModelsExpsenseAdvancedInfo address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Адрес маршрута по доставке
   * @return address
  **/
  @ApiModelProperty(value = "Адрес маршрута по доставке")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OmegaAPIAreasPublicModelsExpsenseAdvancedInfo omegaAPIAreasPublicModelsExpsenseAdvancedInfo = (OmegaAPIAreasPublicModelsExpsenseAdvancedInfo) o;
    return Objects.equals(this.contractName, omegaAPIAreasPublicModelsExpsenseAdvancedInfo.contractName) &&
        Objects.equals(this.creditDepth, omegaAPIAreasPublicModelsExpsenseAdvancedInfo.creditDepth) &&
        Objects.equals(this.recepient, omegaAPIAreasPublicModelsExpsenseAdvancedInfo.recepient) &&
        Objects.equals(this.accountNumber, omegaAPIAreasPublicModelsExpsenseAdvancedInfo.accountNumber) &&
        Objects.equals(this.address, omegaAPIAreasPublicModelsExpsenseAdvancedInfo.address);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contractName, creditDepth, recepient, accountNumber, address);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OmegaAPIAreasPublicModelsExpsenseAdvancedInfo {\n");
    
    sb.append("    contractName: ").append(toIndentedString(contractName)).append("\n");
    sb.append("    creditDepth: ").append(toIndentedString(creditDepth)).append("\n");
    sb.append("    recepient: ").append(toIndentedString(recepient)).append("\n");
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

