/*
 * Omega.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * OmegaAPIAreasPublicModelsPublicPrice
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-12-27T17:23:48.058+02:00")
public class OmegaAPIAreasPublicModelsPublicPrice {
  @SerializedName("Name")
  private String name = null;

  /**
   * Уникальный идентификатор прайса
   */
  @JsonAdapter(IdEnum.Adapter.class)
  public enum IdEnum {
    NUMBER_0(0),
    
    NUMBER_1(1),
    
    NUMBER_2(2),
    
    NUMBER_3(3),
    
    NUMBER_4(4),
    
    NUMBER_5(5),
    
    NUMBER_6(6),
    
    NUMBER_7(7),
    
    NUMBER_8(8),
    
    NUMBER_9(9),
    
    NUMBER_10(10),
    
    NUMBER_11(11),
    
    NUMBER_12(12),
    
    NUMBER_13(13),
    
    NUMBER_14(14),
    
    NUMBER_15(15),
    
    NUMBER_16(16),
    
    NUMBER_17(17),
    
    NUMBER_18(18),
    
    NUMBER_19(19),
    
    NUMBER_20(20),
    
    NUMBER_21(21),
    
    NUMBER_22(22),
    
    NUMBER_23(23),
    
    NUMBER_24(24),
    
    NUMBER_25(25),
    
    NUMBER_26(26),
    
    NUMBER_27(27),
    
    NUMBER_28(28),
    
    NUMBER_29(29),
    
    NUMBER_30(30),
    
    NUMBER_31(31),
    
    NUMBER_32(32),
    
    NUMBER_33(33),
    
    NUMBER_34(34),
    
    NUMBER_35(35);

    private Integer value;

    IdEnum(Integer value) {
      this.value = value;
    }

    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static IdEnum fromValue(String text) {
      for (IdEnum b : IdEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<IdEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final IdEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public IdEnum read(final JsonReader jsonReader) throws IOException {
        Integer value = jsonReader.nextInt();
        return IdEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("Id")
  private IdEnum id = null;

  @SerializedName("Status")
  private String status = null;

  public OmegaAPIAreasPublicModelsPublicPrice name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Наименование прайса
   * @return name
  **/
  @ApiModelProperty(value = "Наименование прайса")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public OmegaAPIAreasPublicModelsPublicPrice id(IdEnum id) {
    this.id = id;
    return this;
  }

   /**
   * Уникальный идентификатор прайса
   * @return id
  **/
  @ApiModelProperty(value = "Уникальный идентификатор прайса")
  public IdEnum getId() {
    return id;
  }

  public void setId(IdEnum id) {
    this.id = id;
  }

  public OmegaAPIAreasPublicModelsPublicPrice status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Статус прайса - типы Default - Прайс может быть поставлен в очередь, InProgress - Прайс формируется, ReadyForDownload - Прайс сформирован, доступен для загрузки
   * @return status
  **/
  @ApiModelProperty(value = "Статус прайса - типы Default - Прайс может быть поставлен в очередь, InProgress - Прайс формируется, ReadyForDownload - Прайс сформирован, доступен для загрузки")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OmegaAPIAreasPublicModelsPublicPrice omegaAPIAreasPublicModelsPublicPrice = (OmegaAPIAreasPublicModelsPublicPrice) o;
    return Objects.equals(this.name, omegaAPIAreasPublicModelsPublicPrice.name) &&
        Objects.equals(this.id, omegaAPIAreasPublicModelsPublicPrice.id) &&
        Objects.equals(this.status, omegaAPIAreasPublicModelsPublicPrice.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, id, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OmegaAPIAreasPublicModelsPublicPrice {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

