/*
 * Omega.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierPublicDeliveryContactPerson;
import io.swagger.client.model.OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierPublicDeliveryCourierType;
import io.swagger.client.model.OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierPublicDeliveryServiceType;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierCourierShipmentSettings
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-12-27T17:23:48.058+02:00")
public class OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierCourierShipmentSettings {
  @SerializedName("DeliveryTypes")
  private List<OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierPublicDeliveryCourierType> deliveryTypes = null;

  @SerializedName("Services")
  private List<OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierPublicDeliveryServiceType> services = null;

  @SerializedName("ContactPersons")
  private List<OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierPublicDeliveryContactPerson> contactPersons = null;

  public OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierCourierShipmentSettings deliveryTypes(List<OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierPublicDeliveryCourierType> deliveryTypes) {
    this.deliveryTypes = deliveryTypes;
    return this;
  }

  public OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierCourierShipmentSettings addDeliveryTypesItem(OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierPublicDeliveryCourierType deliveryTypesItem) {
    if (this.deliveryTypes == null) {
      this.deliveryTypes = new ArrayList<OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierPublicDeliveryCourierType>();
    }
    this.deliveryTypes.add(deliveryTypesItem);
    return this;
  }

   /**
   * Get deliveryTypes
   * @return deliveryTypes
  **/
  @ApiModelProperty(value = "")
  public List<OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierPublicDeliveryCourierType> getDeliveryTypes() {
    return deliveryTypes;
  }

  public void setDeliveryTypes(List<OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierPublicDeliveryCourierType> deliveryTypes) {
    this.deliveryTypes = deliveryTypes;
  }

  public OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierCourierShipmentSettings services(List<OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierPublicDeliveryServiceType> services) {
    this.services = services;
    return this;
  }

  public OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierCourierShipmentSettings addServicesItem(OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierPublicDeliveryServiceType servicesItem) {
    if (this.services == null) {
      this.services = new ArrayList<OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierPublicDeliveryServiceType>();
    }
    this.services.add(servicesItem);
    return this;
  }

   /**
   * Get services
   * @return services
  **/
  @ApiModelProperty(value = "")
  public List<OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierPublicDeliveryServiceType> getServices() {
    return services;
  }

  public void setServices(List<OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierPublicDeliveryServiceType> services) {
    this.services = services;
  }

  public OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierCourierShipmentSettings contactPersons(List<OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierPublicDeliveryContactPerson> contactPersons) {
    this.contactPersons = contactPersons;
    return this;
  }

  public OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierCourierShipmentSettings addContactPersonsItem(OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierPublicDeliveryContactPerson contactPersonsItem) {
    if (this.contactPersons == null) {
      this.contactPersons = new ArrayList<OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierPublicDeliveryContactPerson>();
    }
    this.contactPersons.add(contactPersonsItem);
    return this;
  }

   /**
   * Get contactPersons
   * @return contactPersons
  **/
  @ApiModelProperty(value = "")
  public List<OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierPublicDeliveryContactPerson> getContactPersons() {
    return contactPersons;
  }

  public void setContactPersons(List<OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierPublicDeliveryContactPerson> contactPersons) {
    this.contactPersons = contactPersons;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierCourierShipmentSettings omegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierCourierShipmentSettings = (OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierCourierShipmentSettings) o;
    return Objects.equals(this.deliveryTypes, omegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierCourierShipmentSettings.deliveryTypes) &&
        Objects.equals(this.services, omegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierCourierShipmentSettings.services) &&
        Objects.equals(this.contactPersons, omegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierCourierShipmentSettings.contactPersons);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deliveryTypes, services, contactPersons);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OmegaAPIAreasPublicModelsInvoiceSettingsShipmentCourierCourierShipmentSettings {\n");
    
    sb.append("    deliveryTypes: ").append(toIndentedString(deliveryTypes)).append("\n");
    sb.append("    services: ").append(toIndentedString(services)).append("\n");
    sb.append("    contactPersons: ").append(toIndentedString(contactPersons)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

