/*
 * Omega.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.OmegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainAddress;
import io.swagger.client.model.OmegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainRoute;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * OmegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainAddressSettings
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-12-27T17:23:48.058+02:00")
public class OmegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainAddressSettings {
  @SerializedName("Address")
  private OmegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainAddress address = null;

  @SerializedName("Routes")
  private List<OmegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainRoute> routes = null;

  public OmegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainAddressSettings address(OmegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainAddress address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @ApiModelProperty(value = "")
  public OmegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainAddress getAddress() {
    return address;
  }

  public void setAddress(OmegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainAddress address) {
    this.address = address;
  }

  public OmegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainAddressSettings routes(List<OmegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainRoute> routes) {
    this.routes = routes;
    return this;
  }

  public OmegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainAddressSettings addRoutesItem(OmegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainRoute routesItem) {
    if (this.routes == null) {
      this.routes = new ArrayList<OmegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainRoute>();
    }
    this.routes.add(routesItem);
    return this;
  }

   /**
   * Get routes
   * @return routes
  **/
  @ApiModelProperty(value = "")
  public List<OmegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainRoute> getRoutes() {
    return routes;
  }

  public void setRoutes(List<OmegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainRoute> routes) {
    this.routes = routes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OmegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainAddressSettings omegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainAddressSettings = (OmegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainAddressSettings) o;
    return Objects.equals(this.address, omegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainAddressSettings.address) &&
        Objects.equals(this.routes, omegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainAddressSettings.routes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, routes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OmegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainAddressSettings {\n");
    
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    routes: ").append(toIndentedString(routes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

