/*
 * Omega.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * OmegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainRoute
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-12-27T17:23:48.058+02:00")
public class OmegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainRoute {
  @SerializedName("Id")
  private String id = null;

  @SerializedName("RouteCode")
  private String routeCode = null;

  @SerializedName("TimeEndRoute")
  private String timeEndRoute = null;

  @SerializedName("DepartureTime")
  private String departureTime = null;

  public OmegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainRoute id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Уникальный идентификатор маршрута, строка
   * @return id
  **/
  @ApiModelProperty(value = "Уникальный идентификатор маршрута, строка")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public OmegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainRoute routeCode(String routeCode) {
    this.routeCode = routeCode;
    return this;
  }

   /**
   * Наименование (код) маршрута, строка
   * @return routeCode
  **/
  @ApiModelProperty(value = "Наименование (код) маршрута, строка")
  public String getRouteCode() {
    return routeCode;
  }

  public void setRouteCode(String routeCode) {
    this.routeCode = routeCode;
  }

  public OmegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainRoute timeEndRoute(String timeEndRoute) {
    this.timeEndRoute = timeEndRoute;
    return this;
  }

   /**
   * Время закрытия маршрута, строка
   * @return timeEndRoute
  **/
  @ApiModelProperty(value = "Время закрытия маршрута, строка")
  public String getTimeEndRoute() {
    return timeEndRoute;
  }

  public void setTimeEndRoute(String timeEndRoute) {
    this.timeEndRoute = timeEndRoute;
  }

  public OmegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainRoute departureTime(String departureTime) {
    this.departureTime = departureTime;
    return this;
  }

   /**
   * Время выезда авто, строка
   * @return departureTime
  **/
  @ApiModelProperty(value = "Время выезда авто, строка")
  public String getDepartureTime() {
    return departureTime;
  }

  public void setDepartureTime(String departureTime) {
    this.departureTime = departureTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OmegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainRoute omegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainRoute = (OmegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainRoute) o;
    return Objects.equals(this.id, omegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainRoute.id) &&
        Objects.equals(this.routeCode, omegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainRoute.routeCode) &&
        Objects.equals(this.timeEndRoute, omegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainRoute.timeEndRoute) &&
        Objects.equals(this.departureTime, omegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainRoute.departureTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, routeCode, timeEndRoute, departureTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OmegaAPIAreasPublicModelsInvoiceSettingsShipmentPlainPublicPlainRoute {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    routeCode: ").append(toIndentedString(routeCode)).append("\n");
    sb.append("    timeEndRoute: ").append(toIndentedString(timeEndRoute)).append("\n");
    sb.append("    departureTime: ").append(toIndentedString(departureTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

