/*
 * Omega.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.OmegaAPIAreasPublicModelsReponsesDefaultResponseSystemCollectionsGenericIEnumerableOmegaAPIAreasPublicModelsContactPublicContactPerson;
import io.swagger.client.model.OmegaAPIAreasPublicModelsReponsesDefaultResponseSystemString;
import io.swagger.client.model.OmegaAPIAreasPublicModelsRequestModelsContactAddContactParametersRequest;
import io.swagger.client.model.OmegaAPIAreasPublicModelsRequestModelsContactAddContactPhoneParametersRequest;
import io.swagger.client.model.OmegaAPIAreasPublicModelsRequestModelsContactContactDetailsParametersRequest;
import io.swagger.client.model.OmegaAPIAreasPublicModelsRequestModelsContactEditContactParametersRequest;
import io.swagger.client.model.OmegaAPIAreasPublicModelsRequestModelsContactGetContactsParametersRequest;
import io.swagger.client.model.OmegaAPIAreasPublicModelsRequestModelsContactRemoveContactParametersRequest;
import io.swagger.client.model.OmegaAPIAreasPublicModelsRequestModelsContactRemoveContactPhoneParametersRequest;
import io.swagger.client.model.OmegaCommonModelsResponses;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PublicContactsApi
 */
@Ignore
public class PublicContactsApiTest {

    private final PublicContactsApi api = new PublicContactsApi();

    
    /**
     * Добавляет новое контактное лицо.
     *
     * curl -H \&quot;Content-Type: application/json\&quot; -XPOST \&quot;https://public.omega.page/public/api/v1.0/contact/addContact\&quot; -d \&quot;  {      \&quot;Key\&quot;: \&quot;RQzSCdY99JgV0kMtSYx0KTcE9bdWmhai\&quot;,      \&quot;CustomerId\&quot;: \&quot;custId\&quot;,      \&quot;ContactModel\&quot;:      {          \&quot;FirstName\&quot;: \&quot;pApiTestName\&quot;,          \&quot;SecondName\&quot;: \&quot;pApiTestSecondName\&quot;,          \&quot;LastName\&quot;: \&quot;pApiTestLastName\&quot;,          \&quot;Phone\&quot;: \&quot;0123456789\&quot;,       }  }\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void publicContactsAddContactTest() throws ApiException {
        OmegaAPIAreasPublicModelsRequestModelsContactAddContactParametersRequest model = null;
        OmegaAPIAreasPublicModelsReponsesDefaultResponseSystemString response = api.publicContactsAddContact(model);

        // TODO: test validations
    }
    
    /**
     * Добавляет номер телефона.
     *
     * curl -H \&quot;Content-Type: application/json\&quot; -XPOST \&quot;https://public.omega.page/public/api/v1.0/contact/addContactPhone\&quot; -d \&quot;  {      \&quot;Key\&quot;: \&quot;RQzSCdY99JgV0kMtSYx0KTcE9bdWmhai\&quot;,      \&quot;ContactId\&quot; &#x3D; \&quot;test\&quot;,      \&quot;Phone\&quot;: \&quot;1111111111\&quot;,  }\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void publicContactsAddContactPhoneTest() throws ApiException {
        OmegaAPIAreasPublicModelsRequestModelsContactAddContactPhoneParametersRequest model = null;
        OmegaCommonModelsResponses response = api.publicContactsAddContactPhone(model);

        // TODO: test validations
    }
    
    /**
     * Редактирует контактное лицо.
     *
     * curl -H \&quot;Content-Type: application/json\&quot; -XPOST \&quot;https://public.omega.page/public/api/v1.0/contact/editContact\&quot; -d \&quot;  {      \&quot;Key\&quot;: \&quot;RQzSCdY99JgV0kMtSYx0KTcE9bdWmhai\&quot;,      \&quot;ContactModel\&quot;:      {          \&quot;FirstName\&quot;: \&quot;pApiTestName\&quot;,          \&quot;SecondName\&quot;: \&quot;pApiTestSecondName\&quot;,          \&quot;LastName\&quot;: \&quot;pApiTestLastName\&quot;,      }  }\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void publicContactsEditContactTest() throws ApiException {
        OmegaAPIAreasPublicModelsRequestModelsContactEditContactParametersRequest model = null;
        OmegaCommonModelsResponses response = api.publicContactsEditContact(model);

        // TODO: test validations
    }
    
    /**
     * Получает список телефонов контактного лица.
     *
     * curl -H \&quot;Content-Type: application/json\&quot; -XPOST \&quot;https://public.omega.page/public/api/v1.0/contact/getContactDetails\&quot; -d \&quot;  {      \&quot;Key\&quot;: \&quot;RQzSCdY99JgV0kMtSYx0KTcE9bdWmhai\&quot;,      \&quot;ContactId\&quot;: \&quot;test\&quot;,  }\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void publicContactsGetContactDetailsTest() throws ApiException {
        OmegaAPIAreasPublicModelsRequestModelsContactContactDetailsParametersRequest model = null;
        List<String> response = api.publicContactsGetContactDetails(model);

        // TODO: test validations
    }
    
    /**
     * Получает список конактных лиц.
     *
     * curl -H \&quot;Content-Type: application/json\&quot; -XPOST \&quot;https://public.omega.page/public/api/v1.0/contact/getContacts\&quot; -d \&quot;  {      \&quot;Key\&quot;: \&quot;RQzSCdY99JgV0kMtSYx0KTcE9bdWmhai\&quot;,      \&quot;CustomerId\&quot;: \&quot;custId\&quot;  }\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void publicContactsGetContactsTest() throws ApiException {
        OmegaAPIAreasPublicModelsRequestModelsContactGetContactsParametersRequest model = null;
        OmegaAPIAreasPublicModelsReponsesDefaultResponseSystemCollectionsGenericIEnumerableOmegaAPIAreasPublicModelsContactPublicContactPerson response = api.publicContactsGetContacts(model);

        // TODO: test validations
    }
    
    /**
     * Удаляет контактное лицо.
     *
     * curl -H \&quot;Content-Type: application/json\&quot; -XPOST \&quot;https://public.omega.page/public/api/v1.0/contact/removeContact\&quot; -d \&quot;  {      \&quot;Key\&quot;: \&quot;RQzSCdY99JgV0kMtSYx0KTcE9bdWmhai\&quot;,      \&quot;ContactId\&quot;: \&quot;test\&quot;,  }\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void publicContactsRemoveContactTest() throws ApiException {
        OmegaAPIAreasPublicModelsRequestModelsContactRemoveContactParametersRequest model = null;
        OmegaCommonModelsResponses response = api.publicContactsRemoveContact(model);

        // TODO: test validations
    }
    
    /**
     * Удаляет номер телефона.
     *
     * curl -H \&quot;Content-Type: application/json\&quot; -XPOST \&quot;https://public.omega.page/public/api/v1.0/contact/removeContactPhone\&quot; -d \&quot;  {      \&quot;Key\&quot;: \&quot;RQzSCdY99JgV0kMtSYx0KTcE9bdWmhai\&quot;,      \&quot;ContactId\&quot;: \&quot;test\&quot;,      \&quot;Phone\&quot;: \&quot;(111) 1111111\&quot;,  }\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void publicContactsRemoveContactPhoneTest() throws ApiException {
        OmegaAPIAreasPublicModelsRequestModelsContactRemoveContactPhoneParametersRequest model = null;
        OmegaCommonModelsResponses response = api.publicContactsRemoveContactPhone(model);

        // TODO: test validations
    }
    
}
