/*
 * Omega.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.OmegaAPIAreasPublicModelsReponsesDefaultResponseSystemCollectionsGenericIEnumerableOmegaAPIAreasPublicModelsTreePublicCarModel;
import io.swagger.client.model.OmegaAPIAreasPublicModelsReponsesDefaultResponseSystemCollectionsGenericIEnumerableOmegaAPIAreasPublicModelsTreePublicManufacturerModel;
import io.swagger.client.model.OmegaAPIAreasPublicModelsRequestModelsTreeGetCarModelsParametersRequest;
import io.swagger.client.model.OmegaAPIAreasPublicModelsRequestModelsTreeGetManufacturersParametersRequest;
import io.swagger.client.model.OmegaAPIAreasPublicModelsRequestModelsTreeGetModelModificationsParametersRequest;
import io.swagger.client.model.OmegaAPIAreasPublicModelsRequestModelsTreeGetTreeNodeParametersRequest;
import io.swagger.client.model.OmegaAPIAreasPublicModelsTreePublicTreeNode;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PublicTreeApi
 */
@Ignore
public class PublicTreeApiTest {

    private final PublicTreeApi api = new PublicTreeApi();

    
    /**
     * Возвращает список моделей (доступно в пакете GOLD)
     *
     * curl -H \&quot;Content-Type: application/json\&quot; -XPOST \&quot;https://public.omega.page/public/api/v1.0/product/getCarModes\&quot; -d \&quot;  {      \&quot;Key\&quot;: \&quot;RQzSCdY99JgV0kMtSYx0KTcE9bdWmhai\&quot;,      \&quot;ManufacturerId\&quot;: 0,      \&quot;TypeId\&quot;: 0  }\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void publicTreeGetCarModelsTest() throws ApiException {
        OmegaAPIAreasPublicModelsRequestModelsTreeGetCarModelsParametersRequest model = null;
        OmegaAPIAreasPublicModelsReponsesDefaultResponseSystemCollectionsGenericIEnumerableOmegaAPIAreasPublicModelsTreePublicCarModel response = api.publicTreeGetCarModels(model);

        // TODO: test validations
    }
    
    /**
     * Возвращает список производителей (доступно в пакете GOLD)
     *
     * curl -H \&quot;Content-Type: application/json\&quot; -XPOST \&quot;https://public.omega.page/public/api/v1.0/product/getManufacturers\&quot; -d \&quot;  {      \&quot;Key\&quot;: \&quot;RQzSCdY99JgV0kMtSYx0KTcE9bdWmhai\&quot;,      \&quot;typeId\&quot;: 0  }\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void publicTreeGetManufacturersTest() throws ApiException {
        OmegaAPIAreasPublicModelsRequestModelsTreeGetManufacturersParametersRequest model = null;
        OmegaAPIAreasPublicModelsReponsesDefaultResponseSystemCollectionsGenericIEnumerableOmegaAPIAreasPublicModelsTreePublicManufacturerModel response = api.publicTreeGetManufacturers(model);

        // TODO: test validations
    }
    
    /**
     * Возвращает список модификаций (доступно в пакете GOLD)
     *
     * curl -H \&quot;Content-Type: application/json\&quot; -XPOST \&quot;https://public.omega.page/public/api/v1.0/product/getModifications\&quot; -d \&quot;  {      \&quot;Key\&quot;: \&quot;RQzSCdY99JgV0kMtSYx0KTcE9bdWmhai\&quot;,      \&quot;ModelId\&quot;: 0  }\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void publicTreeGetModificationsTest() throws ApiException {
        OmegaAPIAreasPublicModelsRequestModelsTreeGetModelModificationsParametersRequest model = null;
        OmegaAPIAreasPublicModelsReponsesDefaultResponseSystemCollectionsGenericIEnumerableOmegaAPIAreasPublicModelsTreePublicCarModel response = api.publicTreeGetModifications(model);

        // TODO: test validations
    }
    
    /**
     * Возвращает дерево разузловки (доступно в пакете GOLD)
     *
     * curl -H \&quot;Content-Type: application/json\&quot; -XPOST \&quot;https://public.omega.page/public/api/v1.0/product/getTreeNode\&quot; -d \&quot;  {      \&quot;Key\&quot;: \&quot;RQzSCdY99JgV0kMtSYx0KTcE9bdWmhai\&quot;,      \&quot;ModificationId\&quot;: 0  }\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void publicTreeGetTreeNodeTest() throws ApiException {
        OmegaAPIAreasPublicModelsRequestModelsTreeGetTreeNodeParametersRequest model = null;
        List<OmegaAPIAreasPublicModelsTreePublicTreeNode> response = api.publicTreeGetTreeNode(model);

        // TODO: test validations
    }
    
}
