/*
 * Omega.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetAccessoriesParametersRequest;
import io.swagger.client.model.OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetAccumulatorsParametersRequest;
import io.swagger.client.model.OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetBearingsParametersRequest;
import io.swagger.client.model.OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetGarageEquipmentParametersRequest;
import io.swagger.client.model.OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetLampsParametersRequest;
import io.swagger.client.model.OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetManufacturersParametersRequestModel;
import io.swagger.client.model.OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetOilsParametersRequest;
import io.swagger.client.model.OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetOpticParametersRequest;
import io.swagger.client.model.OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetRoadMapParametersRequest;
import io.swagger.client.model.OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest;
import io.swagger.client.model.OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTiresParametersRequest;
import io.swagger.client.model.OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetWheelDiscsParametersRequest;
import io.swagger.client.model.OmegaAPIAreasPublicModelsSearchCatalogPublicManufacturer;
import io.swagger.client.model.OmegaAPIAreasPublicModelsSearchCatalogPublicProductResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PublicSearchCatalogApi
 */
@Ignore
public class PublicSearchCatalogApiTest {

    private final PublicSearchCatalogApi api = new PublicSearchCatalogApi();

    
    /**
     * Возвращает результат спец подбора &#39;Аксессуары/Оборудование/Инструмент&#39; (доступно в пакете PREMIUM)
     *
     * curl -H \&quot;Content-Type: application/json\&quot; -XPOST \&quot;https://public.omega.page/public/api/v1.0/searchcatalog/getAccessories\&quot; -d \&quot;  {      \&quot;Key\&quot;: \&quot;RQzSCdY99JgV0kMtSYx0KTcE9bdWmhai\&quot;  }\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void publicSearchCatalogGetAccessoriesTest() throws ApiException {
        OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetAccessoriesParametersRequest model = null;
        List<OmegaAPIAreasPublicModelsSearchCatalogPublicProductResponse> response = api.publicSearchCatalogGetAccessories(model);

        // TODO: test validations
    }
    
    /**
     * Возвращает результат спец подбора &#39;АКБ&#39; (доступно в пакете PREMIUM)
     *
     * curl -H \&quot;Content-Type: application/json\&quot; -XPOST \&quot;https://public.omega.page/public/api/v1.0/searchcatalog/getAccumulators\&quot; -d \&quot;  {      \&quot;Key\&quot;: \&quot;RQzSCdY99JgV0kMtSYx0KTcE9bdWmhai\&quot;  }\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void publicSearchCatalogGetAccumulatorsTest() throws ApiException {
        OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetAccumulatorsParametersRequest model = null;
        List<OmegaAPIAreasPublicModelsSearchCatalogPublicProductResponse> response = api.publicSearchCatalogGetAccumulators(model);

        // TODO: test validations
    }
    
    /**
     * Возвращает результат спец подбора &#39;Подшипники&#39; (доступно в пакете PREMIUM)
     *
     * curl -H \&quot;Content-Type: application/json\&quot; -XPOST \&quot;https://public.omega.page/public/api/v1.0/searchcatalog/getBearings\&quot; -d \&quot;  {      \&quot;Key\&quot;: \&quot;RQzSCdY99JgV0kMtSYx0KTcE9bdWmhai\&quot;  }\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void publicSearchCatalogGetBearingsTest() throws ApiException {
        OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetBearingsParametersRequest model = null;
        List<OmegaAPIAreasPublicModelsSearchCatalogPublicProductResponse> response = api.publicSearchCatalogGetBearings(model);

        // TODO: test validations
    }
    
    /**
     * Возвращает результат спец подбора &#39;Гаражное оборудование&#39; (доступно в пакете PREMIUM)
     *
     * curl -H \&quot;Content-Type: application/json\&quot; -XPOST \&quot;https://public.omega.page/public/api/v1.0/searchcatalog/getGarageEquipment\&quot; -d \&quot;  {      \&quot;Key\&quot;: \&quot;RQzSCdY99JgV0kMtSYx0KTcE9bdWmhai\&quot;  }\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void publicSearchCatalogGetGarageEquipmentTest() throws ApiException {
        OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetGarageEquipmentParametersRequest model = null;
        List<OmegaAPIAreasPublicModelsSearchCatalogPublicProductResponse> response = api.publicSearchCatalogGetGarageEquipment(model);

        // TODO: test validations
    }
    
    /**
     * Возвращает результат спец подбора &#39;Лампы&#39; (доступно в пакете PREMIUM)
     *
     * curl -H \&quot;Content-Type: application/json\&quot; -XPOST \&quot;https://public.omega.page/public/api/v1.0/searchcatalog/getLamps\&quot; -d \&quot;  {      \&quot;Key\&quot;: \&quot;RQzSCdY99JgV0kMtSYx0KTcE9bdWmhai\&quot;  }\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void publicSearchCatalogGetLampsTest() throws ApiException {
        OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetLampsParametersRequest model = null;
        List<OmegaAPIAreasPublicModelsSearchCatalogPublicProductResponse> response = api.publicSearchCatalogGetLamps(model);

        // TODO: test validations
    }
    
    /**
     * Возвращает список производителей по категории (доступно в пакете PREMIUM)
     *
     * curl -H \&quot;Content-Type: application/json\&quot; -XPOST \&quot;https://public.omega.page/public/api/v1.0/searchcatalog/getManufacturers\&quot; -d \&quot;  {      \&quot;Key\&quot;: \&quot;RQzSCdY99JgV0kMtSYx0KTcE9bdWmhai\&quot;  }\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void publicSearchCatalogGetManufacturersTest() throws ApiException {
        OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetManufacturersParametersRequestModel model = null;
        List<OmegaAPIAreasPublicModelsSearchCatalogPublicManufacturer> response = api.publicSearchCatalogGetManufacturers(model);

        // TODO: test validations
    }
    
    /**
     * Возвращает результат спец подбора &#39;Масла&#39; (доступно в пакете PREMIUM)
     *
     * curl -H \&quot;Content-Type: application/json\&quot; -XPOST \&quot;https://public.omega.page/public/api/v1.0/searchcatalog/getOils\&quot; -d \&quot;  {      \&quot;Key\&quot;: \&quot;RQzSCdY99JgV0kMtSYx0KTcE9bdWmhai\&quot;  }\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void publicSearchCatalogGetOilsTest() throws ApiException {
        OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetOilsParametersRequest model = null;
        List<OmegaAPIAreasPublicModelsSearchCatalogPublicProductResponse> response = api.publicSearchCatalogGetOils(model);

        // TODO: test validations
    }
    
    /**
     * Возвращает результат спец подбора &#39;Кузов и оптика&#39; (доступно в пакете PREMIUM)
     *
     * curl -H \&quot;Content-Type: application/json\&quot; -XPOST \&quot;https://public.omega.page/public/api/v1.0/searchcatalog/getOptic\&quot; -d \&quot;  {      \&quot;Key\&quot;: \&quot;RQzSCdY99JgV0kMtSYx0KTcE9bdWmhai\&quot;  }\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void publicSearchCatalogGetOpticTest() throws ApiException {
        OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetOpticParametersRequest model = null;
        List<OmegaAPIAreasPublicModelsSearchCatalogPublicProductResponse> response = api.publicSearchCatalogGetOptic(model);

        // TODO: test validations
    }
    
    /**
     * Возвращает результат спец подбора &#39;Дорожная карта&#39; (доступно в пакете PREMIUM)
     *
     * curl -H \&quot;Content-Type: application/json\&quot; -XPOST \&quot;https://public.omega.page/public/api/v1.0/searchcatalog/getRoadMap\&quot; -d \&quot;  {      \&quot;Key\&quot;: \&quot;RQzSCdY99JgV0kMtSYx0KTcE9bdWmhai\&quot;  }\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void publicSearchCatalogGetRoadMapTest() throws ApiException {
        OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetRoadMapParametersRequest model = null;
        List<OmegaAPIAreasPublicModelsSearchCatalogPublicProductResponse> response = api.publicSearchCatalogGetRoadMap(model);

        // TODO: test validations
    }
    
    /**
     * Возвращает результат спец подбора &#39;Технические жидкости&#39; (доступно в пакете PREMIUM)
     *
     * curl -H \&quot;Content-Type: application/json\&quot; -XPOST \&quot;https://public.omega.page/public/api/v1.0/searchcatalog/getTechnicalFluids\&quot; -d \&quot;  {      \&quot;Key\&quot;: \&quot;RQzSCdY99JgV0kMtSYx0KTcE9bdWmhai\&quot;  }\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void publicSearchCatalogGetTechnicalFluidsTest() throws ApiException {
        OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTechnicalFluidsParametersRequest model = null;
        List<OmegaAPIAreasPublicModelsSearchCatalogPublicProductResponse> response = api.publicSearchCatalogGetTechnicalFluids(model);

        // TODO: test validations
    }
    
    /**
     * Возвращает результат спец подбора &#39;Шины&#39; (доступно в пакете PREMIUM)
     *
     * curl -H \&quot;Content-Type: application/json\&quot; -XPOST \&quot;https://public.omega.page/public/api/v1.0/searchcatalog/getTires\&quot; -d \&quot;  {      \&quot;Key\&quot;: \&quot;RQzSCdY99JgV0kMtSYx0KTcE9bdWmhai\&quot;  }\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void publicSearchCatalogGetTiresTest() throws ApiException {
        OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetTiresParametersRequest model = null;
        List<OmegaAPIAreasPublicModelsSearchCatalogPublicProductResponse> response = api.publicSearchCatalogGetTires(model);

        // TODO: test validations
    }
    
    /**
     * Возвращает результат спец подбора &#39;Колесные диски&#39; (доступно в пакете PREMIUM)
     *
     * curl -H \&quot;Content-Type: application/json\&quot; -XPOST \&quot;https://public.omega.page/public/api/v1.0/searchcatalog/getWheelDiscs\&quot; -d \&quot;  {      \&quot;Key\&quot;: \&quot;RQzSCdY99JgV0kMtSYx0KTcE9bdWmhai\&quot;  }\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void publicSearchCatalogGetWheelDiscsTest() throws ApiException {
        OmegaAPIAreasPublicModelsRequestModelsSearchCatalogGetWheelDiscsParametersRequest model = null;
        List<OmegaAPIAreasPublicModelsSearchCatalogPublicProductResponse> response = api.publicSearchCatalogGetWheelDiscs(model);

        // TODO: test validations
    }
    
}
